import type { Language } from "../../i18n";

export const threadCopy = {
  zh: {
    searchPlaceholder: "搜索标题和会话内容",
    clear: "清空",
    conversation: "对话",
    external: "外部",
    subagent: "子代理",
    allKinds: "全部类型",
    selectAll: "全选全部会话",
    export: "导出会话",
    import: "导入会话",
    moveToBin: "移动到回收站",
    sync: "同步会话",
    restartChatGpt: "重启 ChatGPT",
    restartChatGptConfirmTitle: "确认重启 ChatGPT？",
    restartChatGptConfirmDescription: "这会关闭并重新启动本机 ChatGPT/Codex。",
    restartChatGptSuccess: "ChatGPT/Codex 已重启",
    repair: "修复可见性",
    bin: "回收站",
    noProject: "未归属项目",
    empty: "暂无 Codex 会话",
    noMatch: "没有匹配的会话",
    untitled: "未命名会话",
    sessions: "条会话",
    listTitle: "标题",
    sessionCount: "会话数",
    conversationTime: "对话时间",
    inputTokens: "输入",
    outputTokens: "输出",
    totalTokens: "总计",
    openFolder: "打开所在目录",
    openFile: "打开 rollout 文件",
    copyId: "复制会话 ID",
    trashTitle: "Codex 会话回收站",
    trashEmpty: "回收站为空",
    restore: "恢复",
    deleteForever: "永久删除",
    emptyBin: "清空回收站",
    close: "关闭",
    pickOne: "请至少选择一条会话",
    confirmTrash: "所选会话将移到本地回收站，可在之后恢复。",
    confirmDelete: "所选会话将被永久删除，且无法恢复。",
    confirmEmpty: "回收站中的所有会话都将被永久删除，且无法恢复。",
    transferPreview: "会话包预览",
    exportHint: "会话包只包含 rollout 文件与本地索引，不包含账号、Token、API Key 或应用设置。",
    importHint: "已存在相同 ID 的会话会自动跳过，不会覆盖本地内容。",
    packageCount: "可处理 {ready} / {total} 条，合计 {size}",
    continueExport: "选择保存位置",
    continueImport: "导入所选会话",
    transfer: "导入/导出",
    duplicate: "已存在",
    ready: "可导入",
    repairTitle: "Codex 会话不可见",
    repairMessage: "校正官方 Codex state DB 中影响侧边栏显示的会话记录，适合账号与 API Key 切换后的会话恢复。",
    repairMode: "修复方式",
    quick: "快速修复",
    quickDesc: "校正 state DB 和会话文件首条元数据，适合日常切号后恢复。",
    deep: "深度修复",
    deepDesc: "在快速修复基础上重建本地会话索引，适合仍不可见时使用。",
    sessionScope: "会话范围",
    allSessions: "全部会话",
    allSessionsDesc: "修复当前列表中的全部会话。",
    selectedSessions: "所选会话",
    selectedSessionsDesc: "仅修复已勾选的 {count} 条会话。",
    selectedEmpty: "先在列表中勾选会话。",
    preview: "查看影响范围",
    previewing: "正在查看…",
    startRepair: "开始修复",
    repairing: "正在修复…",
    previewResult: "预计更新 DB {db} 行、目录 {catalog} 行、会话文件 {files} 个。",
    loading: "正在读取 Codex 会话…",
  },
  en: {
    searchPlaceholder: "Search titles and conversation content",
    clear: "Clear",
    conversation: "Conversation",
    external: "External",
    subagent: "Subagent",
    allKinds: "All types",
    selectAll: "Select all sessions",
    export: "Export sessions",
    import: "Import sessions",
    moveToBin: "Move to Trash",
    sync: "Sync sessions",
    restartChatGpt: "Restart ChatGPT",
    restartChatGptConfirmTitle: "Restart ChatGPT?",
    restartChatGptConfirmDescription: "This closes and relaunches local ChatGPT/Codex.",
    restartChatGptSuccess: "ChatGPT/Codex restarted",
    repair: "Repair visibility",
    bin: "Trash",
    noProject: "No project",
    empty: "No Codex sessions yet",
    noMatch: "No matching sessions",
    untitled: "Untitled session",
    sessions: "sessions",
    listTitle: "Title",
    sessionCount: "Sessions",
    conversationTime: "Conversation time",
    inputTokens: "Input",
    outputTokens: "Output",
    totalTokens: "Total",
    openFolder: "Open containing folder",
    openFile: "Open rollout file",
    copyId: "Copy session ID",
    trashTitle: "Codex Session Trash",
    trashEmpty: "Trash is empty",
    restore: "Restore",
    deleteForever: "Delete permanently",
    emptyBin: "Empty Trash",
    close: "Close",
    pickOne: "Select at least one session",
    confirmTrash: "Selected sessions will move to local Trash and can be restored later.",
    confirmDelete: "Selected sessions will be permanently deleted and cannot be restored.",
    confirmEmpty: "Every session in Trash will be permanently deleted and cannot be restored.",
    transferPreview: "Session package preview",
    exportHint: [
      "The package contains rollout files and the local index only.",
      "Accounts, tokens, API keys, and settings are excluded.",
    ].join(" "),
    importHint: "Sessions with the same ID are skipped and local content is never overwritten.",
    packageCount: "{ready} of {total} ready · {size}",
    continueExport: "Choose save location",
    continueImport: "Import selected sessions",
    transfer: "Import / Export",
    duplicate: "Already exists",
    ready: "Ready",
    repairTitle: "Codex sessions are not visible",
    repairMessage: [
      "Correct session records in the official Codex state DB that affect sidebar visibility",
      "after account or API key changes.",
    ].join(" "),
    repairMode: "Repair method",
    quick: "Quick repair",
    quickDesc: "Correct the state DB and first metadata record in each session file.",
    deep: "Deep repair",
    deepDesc: "Also rebuild the local session index when quick repair is not enough.",
    sessionScope: "Session scope",
    allSessions: "All sessions",
    allSessionsDesc: "Repair every session in the current list.",
    selectedSessions: "Selected sessions",
    selectedSessionsDesc: "Repair the {count} selected sessions only.",
    selectedEmpty: "Select sessions from the list first.",
    preview: "View impact",
    previewing: "Checking…",
    startRepair: "Start repair",
    repairing: "Repairing…",
    previewResult: "Expected changes: DB {db}, catalog {catalog}, rollout files {files}.",
    loading: "Loading Codex sessions…",
  },
} as const;

export type ThreadCopy = (typeof threadCopy)[Language];
