import type { Language } from "../../i18n";

export const threadCopy = {
  zh: {
    searchPlaceholder: "搜索标题和会话内容",
    clear: "清空",
    conversation: "对话",
    external: "外部",
    subagent: "子代理",
    allKinds: "全部类型",
    selectAll: "全选全部会话",
    export: "导出会话",
    import: "导入会话",
    moveToBin: "移动到回收站",
    moveToHome: "对话迁移",
    homeMigrationTarget: "选择目标 Codex Home",
    confirmHomeMigration: "确认迁移对话？",
    homeMigrationSource: "来源",
    homeMigrationDestination: "目标",
    homeMigrationSelection: "所选对话",
    homeMigrationCount: "{count} 条",
    homeMigrationConfirmHint: "迁移后可在 Codex GUI 中继续对话，对话记录和项目路径会保留。"
      + "关联对话会一并迁移，已有对话会跳过。迁移成功的对话会从来源移除，"
      + "仍被其他对话使用的历史记录会保留。请先结束相关任务。",
    migrationHomeUnavailable: "迁移目标暂不可用，请稍后重试。",
    homeMigrationHint: "将所选 {count} 条会话移至另一个 Codex Home，保留对话记录和项目路径。"
      + "关联会话会一并迁移，目标已有的会话会跳过，原目录仍需使用的历史记录会保留。请先结束相关任务。",
    startHomeMigration: "开始迁移",
    noMigrationHome: "请先在设置中添加另一个 Codex Home。",
    sync: "同步会话",
    restartChatGpt: "重启 ChatGPT",
    restartChatGptConfirmTitle: "确认重启 ChatGPT？",
    restartChatGptConfirmDescription: "这会关闭并重新启动本机 ChatGPT/Codex。",
    restartChatGptSuccess: "ChatGPT/Codex 已重启",
    repair: "修复可见性",
    bin: "回收站",
    noProject: "未归属项目",
    empty: "暂无 Codex 会话",
    noMatch: "没有匹配的会话",
    untitled: "未命名会话",
    sessions: "条会话",
    listTitle: "标题",
    sessionCount: "会话数",
    conversationTime: "对话时间",
    account: "所属账户",
    unknownAccount: "账户未知",
    currentAccount: "当前账户",
    migrate: "迁移到当前账户",
    migrateConfirmTitle: "迁移会话到当前账户？",
    migrateConfirmDescription: "这会保留原会话，并创建一个由当前账户继续使用的新会话。",
    migrateSuccess: "会话已迁移到当前账户",
    inputTokens: "输入",
    outputTokens: "输出",
    totalTokens: "总计",
    openFolder: "打开所在目录",
    openFile: "打开 rollout 文件",
    copyId: "复制会话 ID",
    trashTitle: "Codex 会话回收站",
    trashEmpty: "回收站为空",
    restore: "恢复",
    restoreTarget: "恢复到 Codex Home",
    restoreHint: "恢复到所选目录。已有相同会话时会跳过，不会覆盖。",
    deleteForever: "永久删除",
    emptyBin: "清空回收站",
    close: "关闭",
    pickOne: "请至少选择一条会话",
    confirmTrash: "移入回收站后，所选会话将从 Codex 中移除，可随时恢复。",
    confirmDelete: "所选会话将被永久删除，且无法恢复。",
    confirmEmpty: "回收站中的所有会话都将被永久删除，且无法恢复。",
    transferPreview: "会话包预览",
    exportHint: "会话包只包含 rollout 文件与本地索引，不包含账号、Token、API Key 或应用设置。",
    importHint: "已存在相同 ID 的会话会自动跳过，不会覆盖本地内容。",
    packageCount: "可处理 {ready} / {total} 条，合计 {size}",
    continueExport: "选择保存位置",
    continueImport: "导入所选会话",
    transfer: "导入/导出",
    duplicate: "已存在",
    ready: "可导入",
    repairTitle: "Codex 会话不可见",
    repairMessage: "校正官方 Codex state DB 中影响侧边栏显示的会话记录，适合账号与 API Key 切换后的会话恢复。",
    repairMode: "修复方式",
    quick: "快速修复",
    quickDesc: "校正 state DB 和会话文件首条元数据，适合日常切号后恢复。",
    deep: "深度修复",
    deepDesc: "在快速修复基础上重建本地会话索引，适合仍不可见时使用。",
    sessionScope: "会话范围",
    allSessions: "全部会话",
    allSessionsDesc: "修复当前列表中的全部会话。",
    selectedSessions: "所选会话",
    selectedSessionsDesc: "仅修复已勾选的 {count} 条会话。",
    selectedEmpty: "先在列表中勾选会话。",
    preview: "查看影响范围",
    previewing: "正在查看…",
    startRepair: "开始修复",
    repairing: "正在修复…",
    previewResult: "预计更新 DB {db} 行、目录 {catalog} 行、会话文件 {files} 个。",
    loading: "正在读取 Codex 会话…",
  },
  en: {
    searchPlaceholder: "Search titles and conversation content",
    clear: "Clear",
    conversation: "Conversation",
    external: "External",
    subagent: "Subagent",
    allKinds: "All types",
    selectAll: "Select all sessions",
    export: "Export sessions",
    import: "Import sessions",
    moveToBin: "Move to Trash",
    moveToHome: "Conversation migration",
    homeMigrationTarget: "Choose a destination Codex Home",
    confirmHomeMigration: "Confirm conversation migration?",
    homeMigrationSource: "Source",
    homeMigrationDestination: "Destination",
    homeMigrationSelection: "Selected conversations",
    homeMigrationCount: "{count}",
    homeMigrationConfirmHint: "Continue these conversations in Codex GUI with their history and project paths preserved. "
      + "Related conversations are included; existing ones are skipped. Migrated conversations are removed from "
      + "the source, but history still needed by other conversations is kept. Finish related tasks first.",
    migrationHomeUnavailable: "The destination is unavailable. Please try again later.",
    homeMigrationHint: "Move {count} selected sessions to another Codex Home, keeping their history and project paths. "
      + "Related sessions are included. Existing sessions and required source history are kept. Finish related tasks first.",
    startHomeMigration: "Start migration",
    noMigrationHome: "Add another Codex Home in Settings first.",
    sync: "Sync sessions",
    restartChatGpt: "Restart ChatGPT",
    restartChatGptConfirmTitle: "Restart ChatGPT?",
    restartChatGptConfirmDescription: "This closes and relaunches local ChatGPT/Codex.",
    restartChatGptSuccess: "ChatGPT/Codex restarted",
    repair: "Repair visibility",
    bin: "Trash",
    noProject: "No project",
    empty: "No Codex sessions yet",
    noMatch: "No matching sessions",
    untitled: "Untitled session",
    sessions: "sessions",
    listTitle: "Title",
    sessionCount: "Sessions",
    conversationTime: "Conversation time",
    account: "Account",
    unknownAccount: "Unknown account",
    currentAccount: "Current account",
    migrate: "Migrate to current account",
    migrateConfirmTitle: "Migrate sessions to the current account?",
    migrateConfirmDescription: "The original sessions stay intact and new sessions are created for the current account.",
    migrateSuccess: "Sessions migrated to the current account",
    inputTokens: "Input",
    outputTokens: "Output",
    totalTokens: "Total",
    openFolder: "Open containing folder",
    openFile: "Open rollout file",
    copyId: "Copy session ID",
    trashTitle: "Codex Session Trash",
    trashEmpty: "Trash is empty",
    restore: "Restore",
    restoreTarget: "Restore to Codex Home",
    restoreHint: "Restore to the selected home. Existing conversations are skipped without being overwritten.",
    deleteForever: "Delete permanently",
    emptyBin: "Empty Trash",
    close: "Close",
    pickOne: "Select at least one session",
    confirmTrash: "Selected sessions will be removed from Codex and kept in local Trash. You can restore them anytime.",
    confirmDelete: "Selected sessions will be permanently deleted and cannot be restored.",
    confirmEmpty: "Every session in Trash will be permanently deleted and cannot be restored.",
    transferPreview: "Session package preview",
    exportHint: [
      "The package contains rollout files and the local index only.",
      "Accounts, tokens, API keys, and settings are excluded.",
    ].join(" "),
    importHint: "Sessions with the same ID are skipped and local content is never overwritten.",
    packageCount: "{ready} of {total} ready · {size}",
    continueExport: "Choose save location",
    continueImport: "Import selected sessions",
    transfer: "Import / Export",
    duplicate: "Already exists",
    ready: "Ready",
    repairTitle: "Codex sessions are not visible",
    repairMessage: [
      "Correct session records in the official Codex state DB that affect sidebar visibility",
      "after account or API key changes.",
    ].join(" "),
    repairMode: "Repair method",
    quick: "Quick repair",
    quickDesc: "Correct the state DB and first metadata record in each session file.",
    deep: "Deep repair",
    deepDesc: "Also rebuild the local session index when quick repair is not enough.",
    sessionScope: "Session scope",
    allSessions: "All sessions",
    allSessionsDesc: "Repair every session in the current list.",
    selectedSessions: "Selected sessions",
    selectedSessionsDesc: "Repair the {count} selected sessions only.",
    selectedEmpty: "Select sessions from the list first.",
    preview: "View impact",
    previewing: "Checking…",
    startRepair: "Start repair",
    repairing: "Repairing…",
    previewResult: "Expected changes: DB {db}, catalog {catalog}, rollout files {files}.",
    loading: "Loading Codex sessions…",
  },
} as const;

export type ThreadCopy = (typeof threadCopy)[Language];
