import type { Language } from "../../i18n";

export function quotaChartLabels(language: Language) {
  return language === "zh" ? {
    title: "官方账户额度趋势",
    account: "选择或搜索账户",
    interval: "统计时段",
    hour: "每小时",
    sixHours: "每 6 小时",
    day: "每天",
    view: "图表内容",
    drop: "时段下降",
    remaining: "剩余额度",
    primary: "主用量",
    secondary: "次用量",
    points: "百分点",
    unknown: "暂无记录",
    loading: "正在加载额度记录…",
    error: "额度记录暂时无法加载，请稍后刷新。",
    empty: "暂无可展示的额度变化",
    noAccounts: "暂无官方账户",
    dropHint: "按刷新时点累计额度下降；不计入重置回升，缺少记录的时段留空。",
    remainingHint: "展示每次刷新的剩余额度；重置或缺少记录时断开曲线。",
    historyHint: "额度记录随账户用量刷新开始积累，无法补回此前的历史。",
    zoomHint: "拖动下方滑块可查看其他时段或放大细节。",
  } : {
    title: "Official Account Quota Trends",
    account: "Select or search accounts",
    interval: "Time interval",
    hour: "Hourly",
    sixHours: "Every 6 hours",
    day: "Daily",
    view: "Chart view",
    drop: "Interval decrease",
    remaining: "Remaining quota",
    primary: "Primary",
    secondary: "Secondary",
    points: "pp",
    unknown: "No observation",
    loading: "Loading quota history…",
    error: "Quota history could not be loaded. Please refresh later.",
    empty: "No quota changes to display yet",
    noAccounts: "No official accounts",
    dropHint: "Decreases are counted when observed. Resets are excluded; periods without records stay blank.",
    remainingHint: "Remaining quota at each refresh. Lines break at resets or gaps in the records.",
    historyHint: "History builds as account usage refreshes. Earlier history cannot be recovered.",
    zoomHint: "Drag the slider below to explore other periods or zoom in.",
  };
}
