import { StyleSheet } from 'react-native';

export const desktopStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#080b12' },
  workspace: { flex: 1 },
  landscape: { flexDirection: 'row' },
  stage: { flex: 1, overflow: 'hidden', minHeight: 100 },
  fill: { ...StyleSheet.absoluteFillObject },
  toolbar: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center',
    backgroundColor: '#171c28', padding: 8, gap: 4 },
  rail: { flexDirection: 'column', width: 86 },
  tool: { flex: 1, paddingHorizontal: 2, paddingVertical: 5, alignItems: 'center', justifyContent: 'center',
    gap: 4, borderRadius: 10 },
  selected: { backgroundColor: '#304b78' },
  label: { color: '#e7edf8', fontSize: 10 },
  message: { position: 'absolute', top: 12, alignSelf: 'center', maxWidth: 400, backgroundColor: '#222b3aee',
    borderRadius: 12, padding: 12, gap: 8 },
  text: { color: '#e7edf8', fontSize: 14 },
  hint: { color: '#aebad0', fontSize: 12, lineHeight: 18 },
  stats: { position: 'absolute', left: 10, top: 10, color: '#d9e4f4', fontSize: 11,
    backgroundColor: '#111827bb', padding: 5, borderRadius: 5 },
  mouse: { position: 'absolute', right: 18, bottom: 18, width: 170, height: 190,
    borderRadius: 58, borderWidth: 3, borderColor: '#94a4be', backgroundColor: '#dce9ffed', overflow: 'hidden' },
  mouseTop: { flexDirection: 'row', height: 94 },
  mouseButton: { flex: 1, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 2,
    borderColor: '#94a4be' },
  mouseRight: { borderLeftWidth: 2 },
  mouseText: { color: '#526684', fontSize: 12 },
  pressed: { backgroundColor: '#90baff' },
  pad: { flex: 1, alignItems: 'center', justifyContent: 'flex-end', paddingBottom: 12 },
  wheel: { position: 'absolute', top: 14, left: 62, width: 40, borderRadius: 15,
    borderWidth: 2, borderColor: '#8496b0', backgroundColor: '#e5eeff' },
  wheelButton: { height: 30, alignItems: 'center', justifyContent: 'center' },
  grip: { position: 'absolute', left: 61, top: 78, width: 42, height: 36, alignItems: 'center',
    justifyContent: 'center', borderRadius: 12, borderWidth: 2, borderColor: '#8496b0', backgroundColor: '#e5eeff' },
  panel: { position: 'absolute', right: 8, top: 8, bottom: 8, width: '94%', maxWidth: 400,
    backgroundColor: '#202634f5', borderRadius: 16, padding: 16 },
  panelContent: { gap: 14, paddingBottom: 20 },
  heading: { fontSize: 18, color: '#fff', fontWeight: '600' },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  choice: { backgroundColor: '#333d50', paddingVertical: 10, paddingHorizontal: 12, borderRadius: 9 },
  input: { color: '#fff', borderColor: '#5a6981', borderWidth: 1, borderRadius: 9,
    padding: 10, minWidth: 78 },
  keyboard: { position: 'absolute', left: 8, right: 8, bottom: 8, maxWidth: 400, alignSelf: 'center',
    backgroundColor: '#202634f5', padding: 12, borderRadius: 12, gap: 8 },
});
