import { StyleSheet } from 'react-native';
import { CURSOR_SIZE, MOUSE_SIZE, MOUSE_ICON_SIZE }
  from '../../../../../shared/remote-desktop/geometry';

export const desktopStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#080b12' },
  workspace: { flex: 1 },
  landscape: { flexDirection: 'row' },
  stage: { flex: 1, backgroundColor: '#000', overflow: 'hidden', minHeight: 100 },
  fill: { ...StyleSheet.absoluteFillObject },
  toolbar: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center',
    backgroundColor: '#171c28', padding: 8, gap: 4 },
  rail: { width: 86, flexGrow: 0, flexShrink: 0, backgroundColor: '#171c28' },
  railContent: { flexDirection: 'column', alignItems: 'stretch', justifyContent: 'flex-start', gap: 8 },
  tool: { flex: 1, paddingHorizontal: 2, paddingVertical: 5, alignItems: 'center', justifyContent: 'center',
    gap: 4, borderRadius: 10 },
  railTool: { flex: 0, minHeight: 56, paddingVertical: 8 },
  selected: { backgroundColor: '#304b78' },
  label: { color: '#e7edf8', fontSize: 10 },
  message: { position: 'absolute', top: 12, alignSelf: 'center', maxWidth: 400, backgroundColor: '#222b3aee',
    borderRadius: 12, padding: 12, gap: 8 },
  text: { color: '#e7edf8', fontSize: 14 },
  hint: { color: '#aebad0', fontSize: 12, lineHeight: 18 },
  cursor: { position: 'absolute', ...CURSOR_SIZE, zIndex: 2 },
  // Explicit image dimensions override Metro's 3x bitmap dimensions on both native platforms.
  cursorImage: { ...CURSOR_SIZE },
  mouseLayer: { position: 'absolute' },
  mouseIcon: { ...MOUSE_ICON_SIZE, borderRadius: 20, backgroundColor: '#30343be6',
    alignItems: 'center', justifyContent: 'center' },
  mouse: { position: 'absolute', left: 0, top: 0, ...MOUSE_SIZE,
    borderRadius: 40, borderWidth: 2, borderColor: '#94a4be', backgroundColor: '#dce9ffed', overflow: 'hidden' },
  mouseTop: { flexDirection: 'row', height: 64 },
  mouseButton: { flex: 1, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 2,
    borderColor: '#94a4be' },
  mouseRight: { borderLeftWidth: 2 },
  mouseText: { color: '#526684', fontSize: 11 },
  pressed: { backgroundColor: '#90baff' },
  pad: { flex: 1, alignItems: 'center', justifyContent: 'flex-end', paddingBottom: 12 },
  wheel: { position: 'absolute', top: 8, left: 44, width: 28, height: 46, borderRadius: 15,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 2, borderColor: '#8496b0', backgroundColor: '#e5eeff' },
  grip: { position: 'absolute', left: 42, top: 52, width: 32, height: 28, alignItems: 'center',
    justifyContent: 'center', borderRadius: 12, borderWidth: 2, borderColor: '#8496b0', backgroundColor: '#e5eeff' },
  panel: { position: 'absolute', right: 8, top: 8, bottom: 8, width: '94%', maxWidth: 400,
    backgroundColor: '#202634f5', borderRadius: 16, padding: 16 },
  panelContent: { gap: 14, paddingBottom: 20 },
  heading: { fontSize: 18, color: '#fff', fontWeight: '600' },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  choice: { backgroundColor: '#333d50', paddingVertical: 10, paddingHorizontal: 12, borderRadius: 9 },
  input: { color: '#fff', borderColor: '#5a6981', borderWidth: 1, borderRadius: 9,
    padding: 10, minWidth: 78 },
  keyboard: { position: 'absolute', left: 8, right: 8, bottom: 8, maxWidth: 400, alignSelf: 'center',
    backgroundColor: '#202634', padding: 12, borderRadius: 12, gap: 8, zIndex: 3 },
  keyboardCompact: { padding: 6, gap: 4, bottom: 4 },
  keyboardRow: { flexDirection: 'row', gap: 6, alignItems: 'center' },
  keyboardInput: { flex: 1, minWidth: 0, fontSize: 14 },
  keyboardInputCompact: { paddingVertical: 4, height: 36 },
  keyboardButtonCompact: { paddingVertical: 6, paddingHorizontal: 10 },
});
