import { Platform, StyleSheet } from 'react-native';
import { palette } from '../styles';
import { GRAPH_ROW_HEIGHT } from '../../../../../shared/remote-chat/gitGraph';

export const gitStyles = StyleSheet.create({
  fill: { flex: 1, minWidth: 0 },
  toolbar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, gap: 12 },
  branch: { fontSize: 14, fontWeight: '700', color: palette.ink },
  branchButton: { flex: 1, minWidth: 0, minHeight: 44, justifyContent: 'center' },
  tracking: { paddingHorizontal: 16, paddingBottom: 6, color: palette.muted, fontSize: 11 },
  viewToggle: { flexDirection: 'row', gap: 2, backgroundColor: '#f2f5f3', borderRadius: 6 },
  modeButton: { paddingHorizontal: 10, minHeight: 36, justifyContent: 'center', borderRadius: 6 },
  activeMode: { backgroundColor: '#dcefe6' },
  areaTitle: { fontSize: 12, fontWeight: '700', color: palette.ink, paddingVertical: 8 },
  menu: { position: 'absolute', top: 48, zIndex: 20, maxWidth: 400, width: '92%', alignSelf: 'center',
    borderWidth: 1, borderColor: palette.border, borderRadius: 10, padding: 12,
    backgroundColor: '#fafcfb', elevation: 8, boxShadow: '0 4px 20px #17211b22' },
  menuHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  menuScroll: { maxHeight: 320 },
  menuHint: { maxWidth: 400, fontSize: 12, lineHeight: 18, color: palette.muted, marginVertical: 8 },
  branchRow: { minHeight: 44, gap: 5, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#edf1ef' },
  search: { padding: 10, borderWidth: 1, borderColor: palette.border, borderRadius: 6, fontSize: 12 },
  actionOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  actionButton: { padding: 10, borderRadius: 6, borderWidth: 1, borderColor: palette.border },
  button: { padding: 12, alignItems: 'center', justifyContent: 'center' },
  buttonText: { fontSize: 13, color: palette.green, fontWeight: '600' },
  project: { paddingHorizontal: 16, paddingBottom: 12, fontSize: 11, color: palette.muted },
  notice: { maxWidth: 400, marginHorizontal: 16, marginVertical: 8,
    fontSize: 12, lineHeight: 18, color: palette.muted },
  error: { maxWidth: 400, marginHorizontal: 16, marginVertical: 8,
    fontSize: 12, lineHeight: 18, color: palette.danger },
  tabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: palette.border },
  tab: { flex: 1, padding: 12, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  selectedTab: { borderBottomColor: palette.green },
  loading: { padding: 6 },
  selection: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16 },
  checkButton: { minHeight: 44, minWidth: 32, flexDirection: 'row', alignItems: 'center', gap: 8 },
  check: { color: palette.green, fontSize: 24 },
  meta: { fontSize: 10, lineHeight: 16, color: palette.muted },
  file: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 16,
    borderBottomWidth: 1, borderBottomColor: '#eef2ef' },
  fileButton: { flex: 1, flexDirection: 'row', gap: 10, alignItems: 'center', paddingVertical: 14 },
  status: { fontSize: 11, minWidth: 22, color: palette.green },
  conflict: { color: palette.danger },
  path: { fontSize: 12, lineHeight: 18, color: palette.ink },
  form: { paddingHorizontal: 16, paddingVertical: 10, gap: 8, borderTopWidth: 1, borderTopColor: palette.border },
  input: { minHeight: 60, maxHeight: 100, textAlignVertical: 'top', color: palette.ink,
    borderWidth: 1, borderColor: palette.border, borderRadius: 8, padding: 10, fontSize: 13 },
  hint: { maxWidth: 400, fontSize: 11, lineHeight: 16, color: palette.muted },
  submit: { padding: 12, alignItems: 'center', backgroundColor: palette.green, borderRadius: 8 },
  submitText: { fontSize: 13, fontWeight: '700', color: '#fff' },
  disabled: { opacity: .4 },
  detailTitle: { paddingHorizontal: 16, paddingVertical: 12, fontSize: 12, lineHeight: 18,
    color: palette.ink, backgroundColor: '#f4f7f5' },
  diff: { fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace', fontSize: 11, lineHeight: 18,
    color: palette.ink, padding: 12 },
  added: { backgroundColor: '#e8f5ec', color: '#166b40' },
  removed: { backgroundColor: '#ffeded', color: '#a73535' },
  historyRow: { flexDirection: 'row', height: GRAPH_ROW_HEIGHT, alignItems: 'center' },
  historyText: { width: 310, gap: 4 },
  subject: { fontSize: 12, lineHeight: 18, color: palette.ink, fontWeight: '600' },
  refs: { flexDirection: 'row', gap: 4 },
  ref: { maxWidth: 230, fontSize: 10, lineHeight: 14, color: palette.green, backgroundColor: '#e7f5ef',
    borderRadius: 4, paddingHorizontal: 5, paddingVertical: 2 },
});
