import { Platform, StyleSheet } from 'react-native';
import { palette } from '../styles';
import { GRAPH_ROW_HEIGHT } from '../../../../../shared/remote-chat/gitGraph';

export const gitStyles = StyleSheet.create({
  fill: { flex: 1, minWidth: 0 },
  toolbar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, gap: 8 },
  branch: { flexShrink: 1, fontSize: 14, fontWeight: '700', color: palette.ink },
  branchButton: { flex: 1, minWidth: 0, minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 8 },
  syncButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8 },
  tracking: { paddingHorizontal: 16, paddingBottom: 6, color: palette.muted, fontSize: 11 },
  viewToggle: { flexDirection: 'row', gap: 2, padding: 3, backgroundColor: '#f2f5f3', borderRadius: 8 },
  modeButton: { paddingHorizontal: 9, minHeight: 30, justifyContent: 'center', borderRadius: 6 },
  activeMode: { backgroundColor: '#dcefe6' },
  activeViewMode: { backgroundColor: '#fff' },
  areaTitle: { fontSize: 12, fontWeight: '700', color: palette.ink, paddingVertical: 8 },
  areaRow: { marginTop: 4, backgroundColor: '#f8faf9' },
  areaHeading: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 },
  areaDot: { width: 5, height: 5, borderRadius: 3 },
  areaCount: { marginLeft: 'auto', fontSize: 10, minWidth: 22, textAlign: 'center',
    paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, overflow: 'hidden' },
  menu: { position: 'absolute', top: 48, zIndex: 20, maxWidth: 400, width: '92%', alignSelf: 'center',
    borderWidth: 1, borderColor: palette.border, borderRadius: 10, padding: 12,
    backgroundColor: '#fafcfb', elevation: 8, boxShadow: '0 4px 20px #17211b22' },
  menuHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  menuScroll: { maxHeight: 320 },
  menuHint: { maxWidth: 400, fontSize: 12, lineHeight: 18, color: palette.muted, marginVertical: 8 },
  branchRow: { minHeight: 44, gap: 5, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#edf1ef' },
  search: { padding: 10, borderWidth: 1, borderColor: palette.border, borderRadius: 6, fontSize: 12 },
  actionOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  actionButton: { padding: 10, borderRadius: 6, borderWidth: 1, borderColor: palette.border },
  button: { padding: 12, alignItems: 'center', justifyContent: 'center' },
  buttonText: { fontSize: 13, color: palette.green, fontWeight: '600' },
  project: { paddingHorizontal: 16, paddingBottom: 10, fontSize: 11, color: palette.muted },
  notice: { maxWidth: 400, marginHorizontal: 16, marginVertical: 8,
    fontSize: 12, lineHeight: 18, color: palette.muted },
  error: { maxWidth: 400, marginHorizontal: 16, marginVertical: 8,
    fontSize: 12, lineHeight: 18, color: palette.danger },
  tabs: { flexDirection: 'row', marginHorizontal: 16, padding: 3, gap: 4,
    backgroundColor: '#f2f5f3', borderRadius: 10 },
  tab: { flex: 1, minHeight: 38, justifyContent: 'center', alignItems: 'center', borderRadius: 8 },
  selectedTab: { backgroundColor: '#fff', boxShadow: '0 1px 3px #17211b0d' },
  tabText: { fontSize: 13, color: palette.muted, fontWeight: '500' },
  selectedTabText: { color: palette.green, fontWeight: '600' },
  loading: { padding: 6 },
  selection: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 16, paddingVertical: 4 },
  checkButton: { minHeight: 44, minWidth: 30, flexDirection: 'row', alignItems: 'center', gap: 8 },
  check: { width: 17, height: 17, borderRadius: 5, borderWidth: 1, borderColor: '#cbd7d1',
    backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  checked: { backgroundColor: '#e5f2eb', borderColor: '#82b3a2' },
  treeIcon: { width: 20, height: 20, flexShrink: 0 },
  chevronSlot: { width: 12, alignItems: 'center', justifyContent: 'center' },
  meta: { fontSize: 10, lineHeight: 16, color: palette.muted },
  file: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16 },
  fileButton: { flex: 1, flexDirection: 'row', gap: 7, alignItems: 'center', minHeight: 44, paddingVertical: 8 },
  status: { fontSize: 10, lineHeight: 16, minWidth: 22, textAlign: 'center',
    paddingHorizontal: 4, borderRadius: 5, overflow: 'hidden' },
  folderCount: { color: palette.muted },
  conflict: { color: palette.danger },
  path: { fontSize: 13, lineHeight: 19, color: palette.ink },
  form: { paddingHorizontal: 16, paddingVertical: 10, gap: 8, borderTopWidth: 1, borderTopColor: palette.border },
  input: { minHeight: 52, maxHeight: 100, textAlignVertical: 'top', color: palette.ink,
    borderWidth: 1, borderColor: palette.border, backgroundColor: '#fafcfb',
    borderRadius: 10, padding: 10, fontSize: 13 },
  hint: { maxWidth: 400, fontSize: 11, lineHeight: 16, color: palette.muted },
  submit: { padding: 12, alignItems: 'center', backgroundColor: palette.green, borderRadius: 8 },
  submitText: { fontSize: 13, fontWeight: '700', color: '#fff' },
  disabled: { opacity: .4 },
  detailTitle: { paddingHorizontal: 16, paddingVertical: 12, fontSize: 12, lineHeight: 18,
    color: palette.ink, backgroundColor: '#f4f7f5' },
  diff: { fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace', fontSize: 11, lineHeight: 18,
    color: palette.ink, padding: 12 },
  added: { backgroundColor: '#e8f5ec', color: '#166b40' },
  removed: { backgroundColor: '#ffeded', color: '#a73535' },
  historyRow: { flexDirection: 'row', height: GRAPH_ROW_HEIGHT, alignItems: 'center' },
  historyText: { width: 310, gap: 4 },
  subject: { fontSize: 12, lineHeight: 18, color: palette.ink, fontWeight: '600' },
  refs: { flexDirection: 'row', gap: 4 },
  ref: { maxWidth: 230, fontSize: 10, lineHeight: 14, color: palette.green, backgroundColor: '#e7f5ef',
    borderRadius: 4, paddingHorizontal: 5, paddingVertical: 2 },
});
