import { StyleSheet } from 'react-native';

export const colors = {
  ink: '#20332e', muted: '#7c8b86', green: '#087f69', blue: '#527cb4', danger: '#bd5454',
  canvas: '#f5f7f7', surface: '#ffffff', border: '#e5ece9', paleGreen: '#e8f4ef',
};

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.canvas },
  navigation: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, minHeight: 60,
    backgroundColor: colors.surface, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  back: { width: 44, minHeight: 44, justifyContent: 'center', alignItems: 'center', borderRadius: 14 },
  pageTitle: { flex: 1, textAlign: 'center', color: colors.ink, fontSize: 18, fontWeight: '600' },
  list: { flex: 1 },
  listContent: { flexGrow: 1, padding: 20, paddingBottom: 32, width: '100%', maxWidth: 640, alignSelf: 'center' },
  sources: { gap: 14, marginBottom: 28 },
  connection: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  connectionDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.green },
  offlineDot: { backgroundColor: colors.muted },
  connectionName: { flexShrink: 1, fontSize: 13, color: colors.ink },
  caption: { fontSize: 11, lineHeight: 17, color: colors.muted },
  sectionLabel: { color: colors.muted, fontSize: 12, fontWeight: '500' },
  sourceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  sourceCard: { flex: 1, minWidth: 140, backgroundColor: colors.surface, borderRadius: 18,
    borderWidth: 1, borderColor: colors.border, padding: 16, gap: 14 },
  sourceChevron: { position: 'absolute', right: 16, top: 29 },
  sourceIcon: { width: 42, height: 42, borderRadius: 13, backgroundColor: colors.paleGreen,
    justifyContent: 'center', alignItems: 'center' },
  computerIcon: { backgroundColor: '#edf2f9' },
  sourceCopy: { flexGrow: 1 },
  sourceTitle: { fontSize: 14, lineHeight: 22, fontWeight: '600', color: colors.ink },
  hint: { flexDirection: 'row', alignItems: 'flex-start', gap: 6 },
  hintText: { flex: 1, fontSize: 12, lineHeight: 18, color: colors.muted },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  sectionTitle: { fontSize: 16, fontWeight: '600', color: colors.ink },
  count: { fontSize: 12, color: colors.muted },
  empty: { alignItems: 'center', justifyContent: 'center', paddingVertical: 56, paddingHorizontal: 12,
    backgroundColor: colors.surface, borderRadius: 20, borderWidth: 1, borderColor: colors.border },
  emptyHalo: { width: 96, height: 96, borderRadius: 48, backgroundColor: '#f4f9f6',
    justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
  emptyIcon: { width: 68, height: 68, borderRadius: 22, backgroundColor: colors.paleGreen,
    justifyContent: 'center', alignItems: 'center' },
  emptyBadge: { position: 'absolute', right: 7, bottom: 10, width: 25, height: 25, borderRadius: 13,
    borderWidth: 3, borderColor: colors.surface, backgroundColor: colors.green,
    justifyContent: 'center', alignItems: 'center' },
  emptyTitle: { fontSize: 17, fontWeight: '600', color: colors.ink, marginBottom: 10 },
  emptyText: { fontSize: 12, lineHeight: 22, color: colors.muted, textAlign: 'center', maxWidth: 320 },
  card: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.border,
    padding: 16, gap: 14, marginBottom: 12 },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  fileIcon: { width: 42, height: 46, borderRadius: 12, backgroundColor: '#f0f5f3',
    justifyContent: 'center', alignItems: 'center' },
  fileCopy: { flex: 1, gap: 5 },
  title: { color: colors.ink, fontSize: 15, lineHeight: 22, fontWeight: '600' },
  statusRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  status: { color: colors.green, fontSize: 11, fontWeight: '500' },
  statusBadge: { borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3, backgroundColor: colors.paleGreen },
  pausedBadge: { backgroundColor: '#f3f1eb' },
  paused: { color: '#8f7b50' },
  failedBadge: { backgroundColor: '#fbeeee' },
  progressCopy: { gap: 8 },
  track: { height: 5, borderRadius: 4, backgroundColor: '#edf2f0', overflow: 'hidden' },
  progress: { height: '100%', backgroundColor: colors.green, borderRadius: 4 },
  pausedProgress: { backgroundColor: '#b8a77e' },
  failedProgress: { backgroundColor: colors.danger },
  toolbar: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', alignItems: 'center' },
  cardActions: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border,
    paddingTop: 12, justifyContent: 'space-between' },
  button: { minHeight: 44, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 14,
    borderRadius: 12, backgroundColor: colors.paleGreen, flexDirection: 'row', gap: 6 },
  buttonText: { fontSize: 13, color: colors.green, fontWeight: '600' },
  deleteButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5,
    minHeight: 44, paddingHorizontal: 8, borderRadius: 10 },
  deleteText: { color: colors.muted, fontSize: 12 },
  danger: { color: colors.danger },
  disabled: { opacity: 0.45 },
  pressed: { opacity: 0.65 },
  text: { fontSize: 13, lineHeight: 20, color: colors.muted, maxWidth: 400 },
  message: { fontSize: 13, lineHeight: 20, color: colors.green, maxWidth: 400, marginVertical: 8 },
  error: { fontSize: 13, lineHeight: 20, color: colors.danger, maxWidth: 400, marginVertical: 8 },
  browserHeader: { gap: 12, marginBottom: 20 },
  browserToolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  path: { color: colors.ink, fontSize: 14, lineHeight: 22 },
  row: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14,
    backgroundColor: colors.surface, borderRadius: 14, borderWidth: 1, borderColor: colors.border, marginBottom: 8 },
  name: { color: colors.ink, fontSize: 14, lineHeight: 21, flex: 1 },
});
