import { expect, test } from '@playwright/test';
import { connect, fixtureUrl, login, openChatList, screenshot, state } from './chat-helpers';

test('tools open Git changes, commit only checked files and draw merge history', async ({ page, request }, info) => {
  await request.post(`${fixtureUrl}/test/reset`);
  await login(page); await connect(page); await openChatList(page);
  await page.getByRole('button', { name: '移动端聊天体验', exact: true }).click();
  await page.getByRole('button', { name: '打开工具', exact: true }).click();
  await expect(page.getByRole('button', { name: '终端', exact: true })).toBeVisible();
  await screenshot(page, info, 'tools-menu');
  await page.getByRole('button', { name: 'Git', exact: true }).click();
  const drawer = page.getByRole('dialog', { name: 'Git', exact: true });
  await expect(drawer).toBeVisible();
  const app = drawer.getByRole('checkbox', { name: '选择 src/app.ts', exact: true });
  await expect(app).toBeVisible();
  await app.check();
  await drawer.getByRole('button', { name: /M src\/app.ts/ }).click();
  await expect(drawer.locator('.git-diff')).toContainText('+new code');
  await screenshot(page, info, 'git-diff');
  await drawer.getByRole('button', { name: 'src/app.ts', exact: true }).click();
  await expect(app).toBeChecked();
  const message = drawer.getByRole('textbox', { name: '提交说明' });
  await message.fill('更新应用');
  await screenshot(page, info, 'git-changes');
  await message.fill('fail');
  await drawer.getByRole('button', { name: '提交 1 个文件', exact: true }).click();
  await expect(drawer.getByRole('alert')).toContainText('暂时无法完成此操作');
  await expect(app).toBeChecked();
  await expect(message).toHaveValue('fail');
  await message.fill('更新应用');
  await drawer.getByRole('button', { name: '提交 1 个文件', exact: true }).click();
  await expect(drawer.getByRole('status')).toContainText('已提交');
  await expect(app).toHaveCount(0);
  await expect(drawer.getByRole('checkbox', { name: '选择 README.md', exact: true })).not.toBeChecked();
  const submitted = (await state(request)).operations.filter(op => op.operation === 'guiGitCommit').at(-1);
  expect(submitted?.files).toEqual([{ path: 'src/app.ts', version: 'app-v1' }]);
  await drawer.getByRole('tab', { name: '提交记录', exact: true }).click();
  await expect(drawer.locator('.git-history-row')).toHaveCount(3);
  await drawer.getByRole('button', { name: '加载更多提交' }).click();
  await expect(drawer.locator('.git-history-row')).toHaveCount(6);
  await expect(drawer.locator('svg circle')).toHaveCount(6);
  await expect(drawer.locator('svg line')).not.toHaveCount(0);
  await expect(drawer).toContainText('feature/git');
  await screenshot(page, info, 'git-history');
  const bounds = (await drawer.boundingBox())!;
  expect(bounds.width).toBeLessThanOrEqual(page.viewportSize()!.width);
  await drawer.locator('.git-history-row').first().click();
  await expect(drawer.locator('.git-diff')).toContainText('committed change');
  await drawer.getByRole('button', { name: '关闭 Git' }).click();
  await page.getByRole('button', { name: '打开工具', exact: true }).click();
  await page.getByRole('button', { name: '终端', exact: true }).click();
  await expect(page.getByRole('dialog', { name: '远程终端', exact: true })).toBeVisible();
  await expect(page.locator('.xterm-rows')).toContainText('Remote shell ready');
});
