import { StyleSheet } from 'react-native';

export const totpStyles = StyleSheet.create({
  trigger: {
    minHeight: 34,
    paddingHorizontal: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#bde8d8',
    borderRadius: 10,
    backgroundColor: '#e6f8f1',
  },
  triggerText: { color: '#14806f', fontSize: 12, fontWeight: '800' },
  managerBody: { maxHeight: 590 },
  managerBodyContent: { paddingBottom: 8 },
  intro: { color: '#6f8177', fontSize: 12, lineHeight: 18, marginBottom: 14 },
  empty: {
    minHeight: 180,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#dce8df',
    borderRadius: 15,
    backgroundColor: '#f7faf7',
    padding: 24,
  },
  emptyIcon: { color: '#18af8c', fontSize: 32, fontWeight: '900' },
  emptyTitle: { color: '#13231c', fontSize: 16, fontWeight: '800', marginTop: 10 },
  emptyText: { color: '#6f8177', fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 6 },
  codeCard: {
    borderWidth: 1,
    borderColor: '#dce8df',
    borderRadius: 15,
    backgroundColor: '#ffffff',
    padding: 15,
    marginBottom: 11,
  },
  codeHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  codeIdentity: { flex: 1, minWidth: 0 },
  issuer: { color: '#13231c', fontSize: 15, fontWeight: '800' },
  account: { color: '#6f8177', fontSize: 11, marginTop: 4 },
  codeActions: { flexDirection: 'row', gap: 6 },
  smallAction: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8, backgroundColor: '#eef5f1' },
  smallActionDanger: { backgroundColor: '#fff0ef' },
  smallActionText: { color: '#356354', fontSize: 11, fontWeight: '700' },
  smallActionDangerText: { color: '#bd3c35' },
  codeButton: { marginTop: 15 },
  codeRow: { flexDirection: 'row', alignItems: 'center' },
  codeValue: { flex: 1, color: '#0b8065', fontSize: 28, fontWeight: '900', letterSpacing: 2 },
  countdown: { color: '#6f8177', fontSize: 12, fontWeight: '800' },
  progressTrack: { height: 4, overflow: 'hidden', borderRadius: 3, backgroundColor: '#dce8df', marginTop: 10 },
  progressFill: { height: '100%', borderRadius: 3, backgroundColor: '#18af8c' },
  fieldLabel: { color: '#13231c', fontSize: 13, fontWeight: '700', marginBottom: 7, marginTop: 13 },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: '#cbdcd0',
    borderRadius: 10,
    backgroundColor: '#fbfdfb',
    color: '#13231c',
    fontSize: 15,
    paddingHorizontal: 13,
  },
  secretRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  secretInput: { flex: 1 },
  revealButton: { minHeight: 46, justifyContent: 'center', paddingHorizontal: 12 },
  revealText: { color: '#14806f', fontSize: 12, fontWeight: '800' },
  hint: { color: '#6f8177', fontSize: 11, lineHeight: 17, marginTop: 6 },
  qrButton: {
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: '#e8f8fb',
    marginBottom: 4,
  },
  qrButtonText: { color: '#168da2', fontSize: 14, fontWeight: '800' },
  error: { color: '#bd3c35', fontSize: 12, lineHeight: 18, marginTop: 10 },
  optionRow: { flexDirection: 'row', gap: 8 },
  option: {
    flex: 1,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: '#eef3f0',
  },
  optionActive: { backgroundColor: '#d8f4ec', borderWidth: 1, borderColor: '#8fdcca' },
  optionText: { color: '#6f8177', fontSize: 12, fontWeight: '700' },
  optionTextActive: { color: '#0b8065' },
  formScroll: { maxHeight: 570 },
  formContent: { paddingBottom: 8 },
  cameraRoot: { flex: 1, backgroundColor: '#06140f' },
  camera: { flex: 1 },
  cameraOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 28,
  },
  cameraTitle: { color: '#fff', fontSize: 20, fontWeight: '900', marginTop: 36 },
  scanFrame: { width: 260, height: 260, borderWidth: 3, borderColor: '#a7e733', borderRadius: 24 },
  cameraHint: { color: '#fff', fontSize: 13, lineHeight: 19, textAlign: 'center' },
  cameraClose: {
    minWidth: 120,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#ffffff',
  },
  cameraCloseText: { color: '#13231c', fontSize: 15, fontWeight: '800' },
  permissionBox: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28, backgroundColor: '#f7faf7' },
  permissionTitle: { color: '#13231c', fontSize: 18, fontWeight: '800', textAlign: 'center' },
  permissionText: { color: '#6f8177', fontSize: 13, lineHeight: 20, textAlign: 'center', marginTop: 9 },
});
