import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, LoaderCircle, Plus, Trash2, X } from "lucide-react";
import { fetchPromptPlugins, installPromptPlugin, publishPromptPlugin, removePromptPlugin, setPromptPluginEnabled } from "../../api/backend";
import type { PromptPluginItem, PromptPluginType } from "../../types";
import type { SkillsMarketPageProps, SkillsMarketNavigationProps } from "../skillsMarket/types";
import { SkillsMarketToolbar } from "../skillsMarket/SkillsMarketToolbar";
import styles from "./index.module.less";

type Props = SkillsMarketPageProps & SkillsMarketNavigationProps;

function typeLabel(type: PromptPluginType, t: Props["t"]) { return t(type === "filter" ? "skills.prompt.filter" : "skills.prompt.injection"); }

function PublishModal({ onClose, onPublished, t }: { onClose: () => void; onPublished: () => Promise<void>; t: Props["t"] }) {
  const [name, setName] = useState(""); const [version, setVersion] = useState("1.0.0"); const [type, setType] = useState<PromptPluginType>("injection"); const [text, setText] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async () => { if (!name.trim() || !version.trim() || !text.trim()) return setError(t("skills.prompt.required")); if (type === "filter" && text.trim().length > 500) return setError(t("skills.prompt.filterTooLong")); setBusy(true); try { await publishPromptPlugin({ name, version, type, text }); await onPublished(); onClose(); } catch (caught) { setError(String(caught)); } finally { setBusy(false); } };
  return <div className="modal-backdrop" role="presentation"><div className={`modal ${styles.modal}`} role="dialog" aria-modal="true"><button type="button" className="modal-close" onClick={onClose} aria-label={t("skills.publish.close")}><X size={18} /></button><h2>{t("skills.prompt.publishTitle")}</h2><label>{t("skills.prompt.name")}<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>{t("skills.prompt.version")}<input value={version} onChange={(e) => setVersion(e.target.value)} /></label><div className={styles.typeTabs}>{(["injection", "filter"] as const).map((item) => <button key={item} type="button" className={type === item ? styles.active : ""} onClick={() => setType(item)}>{typeLabel(item, t)}</button>)}</div><label>{t("skills.prompt.text")}<textarea rows={8} maxLength={type === "filter" ? 500 : 5000} value={text} onChange={(e) => setText(e.target.value)} /></label>{error && <p className="feedback-error">{error}</p>}<div className="feedback-actions"><button type="button" className="note-cancel-button" onClick={onClose}>{t("skills.cancel")}</button><button type="button" className="primary-button" disabled={busy} onClick={() => void submit()}>{busy ? <LoaderCircle className="spin" size={15} /> : <Plus size={15} />}{t("skills.prompt.publish")}</button></div></div></div>;
}

export function PromptPluginsMarket({ active, activeTab, authenticated, currentUserId, notify, onLogin, onTabChange, t }: Props) {
  const [items, setItems] = useState<PromptPluginItem[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [publishing, setPublishing] = useState(false); const [busy, setBusy] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { setItems(await fetchPromptPlugins()); setError(null); } catch (caught) { setError(String(caught)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase(); return items.filter((item) => !needle || `${item.name}\n${item.text}`.toLocaleLowerCase().includes(needle)); }, [items, query]);
  const run = async (item: PromptPluginItem, action: "install" | "remove" | "toggle") => { setBusy(item.id); try { if (action === "install") await installPromptPlugin(item.id); else if (action === "remove") await removePromptPlugin(item.id); else await setPromptPluginEnabled(item.id, !item.enabled); notify(t(`skills.prompt.toast.${action}`)); await load(); } catch (caught) { setError(String(caught)); } finally { setBusy(null); } };
  return <div className="skills-market-page"><SkillsMarketToolbar active={active} activeTab={activeTab} loading={loading} onPublish={authenticated ? () => setPublishing(true) : onLogin} onQueryChange={setQuery} onRefresh={() => void load()} onTabChange={onTabChange} query={query} t={t} />{error && <div className="skills-market-error" role="alert">{error}</div>}{loading && !items.length ? <div className="skills-market-state"><LoaderCircle className="spin" size={22} />{t("skills.prompt.loading")}</div> : !filtered.length ? <div className="skills-market-state">{t("skills.prompt.empty")}</div> : <div className={styles.grid}>{filtered.map((item) => <article className={styles.card} key={item.id}><div className={styles.badge}>{typeLabel(item.type, t)}</div><h3>{item.name}</h3><small>v{item.version}</small><p>{item.text}</p><div className={styles.meta}><span><Download size={13} />{item.installCount.toLocaleString()}</span>{currentUserId && item.uploaderId === currentUserId && <span>{t("skills.publisher")}</span>}</div><div className={styles.actions}>{item.installed && <button type="button" disabled={busy === item.id} onClick={() => void run(item, "toggle")}>{item.enabled ? t("skills.prompt.disable") : t("skills.prompt.enable")}</button>}<button type="button" disabled={busy === item.id} onClick={() => void run(item, item.installed ? "remove" : "install")}>{busy === item.id ? <LoaderCircle className="spin" size={14} /> : item.installed ? <Trash2 size={14} /> : <Plus size={14} />}{item.installed ? t("skills.prompt.uninstall") : t("skills.prompt.install")}</button></div></article>)}</div>}{publishing && <PublishModal onClose={() => setPublishing(false)} onPublished={async () => { notify(t("skills.prompt.toast.published")); await load(); }} t={t} />}</div>;
}
