import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  checkRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', columnGap: 4, marginTop: 12 },
  checkLabel: { flexDirection: 'row', alignItems: 'center', minHeight: 44, maxWidth: '100%', gap: 8 },
  checkbox: { width: 20, height: 20, borderRadius: 5, borderWidth: 1, borderColor: '#6f8177',
    alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  checked: { backgroundColor: '#0b8065', borderColor: '#0b8065' },
  tick: { color: '#fff', fontSize: 15, fontWeight: '700' },
  checkText: { color: '#52645b', fontSize: 13, lineHeight: 22, flexShrink: 1 },
  linkButton: { minHeight: 44, justifyContent: 'center', maxWidth: '100%' },
  link: { color: '#08735d', fontSize: 13, lineHeight: 22, textDecorationLine: 'underline' },
  overlay: { flex: 1, backgroundColor: 'rgba(6,20,15,0.5)', justifyContent: 'center', alignItems: 'center',
    padding: 16 },
  card: { width: '100%', maxWidth: 400, maxHeight: '100%', backgroundColor: '#fff', borderRadius: 20,
    padding: 20, flexShrink: 1 },
  reader: { maxWidth: 720, height: '92%' },
  header: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  title: { flex: 1, color: '#13231c', fontSize: 18, lineHeight: 26, fontWeight: '700' },
  closeButton: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  closeText: { color: '#52645b', fontSize: 28 },
  scroll: { flexShrink: 1 },
  content: { paddingBottom: 8 },
  updated: { color: '#6f8177', fontSize: 12, marginBottom: 14 },
  paragraph: { color: '#374d41', fontSize: 14, lineHeight: 26, marginBottom: 12 },
  sectionTitle: { color: '#13231c', fontSize: 16, lineHeight: 25, marginTop: 16, marginBottom: 8 },
  important: { fontWeight: '800' },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, paddingTop: 12 },
  action: { flexGrow: 1, flexBasis: 110, minHeight: 44, padding: 12, borderRadius: 10,
    alignItems: 'center', justifyContent: 'center', backgroundColor: '#eef3f0' },
  primaryAction: { backgroundColor: '#0b8065' },
  actionText: { color: '#374d41', fontSize: 14, fontWeight: '700', textAlign: 'center' },
  primaryText: { color: '#fff' },
});
