import type { DreamSkinAppearance } from "./types";

export type BuiltInDreamSkinTheme = {
  id: string;
  englishName: string;
  nameKey: `dreamSkin.theme.${string}.name`;
  descriptionKey: `dreamSkin.theme.${string}.description`;
  preview: string;
  tone: string;
  appearance: DreamSkinAppearance;
};

export const BUILT_IN_DREAM_SKIN_THEMES = [
  {
    id: "preset-gothic-void-crusade",
    englishName: "Gothic Void Crusade",
    nameKey: "dreamSkin.theme.gothic.name",
    descriptionKey: "dreamSkin.theme.gothic.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-gothic-void-crusade/background.jpg", import.meta.url).href,
    tone: "gothic",
    appearance: "dark",
  },
  {
    id: "preset-rose-reverie",
    englishName: "Rose Reverie",
    nameKey: "dreamSkin.theme.roseReverie.name",
    descriptionKey: "dreamSkin.theme.roseReverie.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-rose-reverie/background.jpg", import.meta.url).href,
    tone: "rose-reverie",
    appearance: "light",
  },
  {
    id: "preset-fortune-at-work",
    englishName: "Fortune at Work",
    nameKey: "dreamSkin.theme.fortuneAtWork.name",
    descriptionKey: "dreamSkin.theme.fortuneAtWork.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-fortune-at-work/background.jpg", import.meta.url).href,
    tone: "fortune",
    appearance: "light",
  },
  {
    id: "preset-coral-horizon",
    englishName: "Coral Horizon",
    nameKey: "dreamSkin.theme.coralHorizon.name",
    descriptionKey: "dreamSkin.theme.coralHorizon.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-coral-horizon/background.jpg", import.meta.url).href,
    tone: "coral",
    appearance: "light",
  },
  {
    id: "preset-sage-daylight",
    englishName: "Sage Daylight",
    nameKey: "dreamSkin.theme.sageDaylight.name",
    descriptionKey: "dreamSkin.theme.sageDaylight.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-sage-daylight/background.jpg", import.meta.url).href,
    tone: "sage",
    appearance: "light",
  },
  {
    id: "preset-spark-studio",
    englishName: "Spark Studio",
    nameKey: "dreamSkin.theme.sparkStudio.name",
    descriptionKey: "dreamSkin.theme.sparkStudio.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-spark-studio/background.jpg", import.meta.url).href,
    tone: "spark",
    appearance: "light",
  },
  {
    id: "preset-cosmic-violet",
    englishName: "Cosmic Violet",
    nameKey: "dreamSkin.theme.cosmicViolet.name",
    descriptionKey: "dreamSkin.theme.cosmicViolet.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-cosmic-violet/background.jpg", import.meta.url).href,
    tone: "cosmic",
    appearance: "dark",
  },
  {
    id: "preset-aqua-resonance",
    englishName: "Aqua Resonance",
    nameKey: "dreamSkin.theme.aquaResonance.name",
    descriptionKey: "dreamSkin.theme.aquaResonance.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-aqua-resonance/background.jpg", import.meta.url).href,
    tone: "aqua",
    appearance: "light",
  },
  {
    id: "preset-midnight-gold",
    englishName: "Midnight Gold",
    nameKey: "dreamSkin.theme.midnightGold.name",
    descriptionKey: "dreamSkin.theme.midnightGold.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-midnight-gold/background.jpg", import.meta.url).href,
    tone: "midnight",
    appearance: "dark",
  },
  {
    id: "preset-celadon-sword-lord",
    englishName: "Celadon Sword Lord",
    nameKey: "dreamSkin.theme.celadonSwordLord.name",
    descriptionKey: "dreamSkin.theme.celadonSwordLord.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-celadon-sword-lord/background.jpg", import.meta.url).href,
    tone: "ancient-male",
    appearance: "light",
  },
  {
    id: "preset-bamboo-flute-scholar",
    englishName: "Bamboo Flute Scholar",
    nameKey: "dreamSkin.theme.bambooFluteScholar.name",
    descriptionKey: "dreamSkin.theme.bambooFluteScholar.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-bamboo-flute-scholar/background.jpg", import.meta.url).href,
    tone: "ancient-male",
    appearance: "light",
  },
  {
    id: "preset-crimson-cloud-general",
    englishName: "Crimson Cloud General",
    nameKey: "dreamSkin.theme.crimsonCloudGeneral.name",
    descriptionKey: "dreamSkin.theme.crimsonCloudGeneral.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-crimson-cloud-general/background.jpg", import.meta.url).href,
    tone: "ancient-male",
    appearance: "dark",
  },
  {
    id: "preset-white-fox-scholar",
    englishName: "White Fox Scholar",
    nameKey: "dreamSkin.theme.whiteFoxScholar.name",
    descriptionKey: "dreamSkin.theme.whiteFoxScholar.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-white-fox-scholar/background.jpg", import.meta.url).href,
    tone: "ancient-male",
    appearance: "light",
  },
  {
    id: "preset-jade-dragon-prince",
    englishName: "Jade Dragon Prince",
    nameKey: "dreamSkin.theme.jadeDragonPrince.name",
    descriptionKey: "dreamSkin.theme.jadeDragonPrince.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-jade-dragon-prince/background.jpg", import.meta.url).href,
    tone: "ancient-male",
    appearance: "light",
  },
  {
    id: "preset-lantern-night-guard",
    englishName: "Lantern Night Guard",
    nameKey: "dreamSkin.theme.lanternNightGuard.name",
    descriptionKey: "dreamSkin.theme.lanternNightGuard.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-lantern-night-guard/background.jpg", import.meta.url).href,
    tone: "ancient-male",
    appearance: "dark",
  },
  {
    id: "preset-snow-crane-swordsman",
    englishName: "Snow Crane Swordsman",
    nameKey: "dreamSkin.theme.snowCraneSwordsman.name",
    descriptionKey: "dreamSkin.theme.snowCraneSwordsman.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-snow-crane-swordsman/background.jpg", import.meta.url).href,
    tone: "ancient-male",
    appearance: "light",
  },
  {
    id: "preset-lotus-spring-healer",
    englishName: "Lotus Spring Healer",
    nameKey: "dreamSkin.theme.lotusSpringHealer.name",
    descriptionKey: "dreamSkin.theme.lotusSpringHealer.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-lotus-spring-healer/background.jpg", import.meta.url).href,
    tone: "ancient-female",
    appearance: "light",
  },
  {
    id: "preset-tea-mountain-youth",
    englishName: "Tea Mountain Youth",
    nameKey: "dreamSkin.theme.teaMountainYouth.name",
    descriptionKey: "dreamSkin.theme.teaMountainYouth.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-tea-mountain-youth/background.jpg", import.meta.url).href,
    tone: "ancient-male",
    appearance: "light",
  },
  {
    id: "preset-dunhuang-lotus-dancer",
    englishName: "Dunhuang Lotus Dancer",
    nameKey: "dreamSkin.theme.dunhuangLotusDancer.name",
    descriptionKey: "dreamSkin.theme.dunhuangLotusDancer.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-dunhuang-lotus-dancer/background.jpg", import.meta.url).href,
    tone: "ancient-female",
    appearance: "light",
  },
  {
    id: "preset-white-fox-maiden",
    englishName: "White Fox Maiden",
    nameKey: "dreamSkin.theme.whiteFoxMaiden.name",
    descriptionKey: "dreamSkin.theme.whiteFoxMaiden.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-white-fox-maiden/background.jpg", import.meta.url).href,
    tone: "ancient-female",
    appearance: "light",
  },
  {
    id: "preset-bamboo-qin-muse",
    englishName: "Bamboo Qin Muse",
    nameKey: "dreamSkin.theme.bambooQinMuse.name",
    descriptionKey: "dreamSkin.theme.bambooQinMuse.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-bamboo-qin-muse/background.jpg", import.meta.url).href,
    tone: "ancient-female",
    appearance: "light",
  },
  {
    id: "preset-campus-cardigan-girl",
    englishName: "Cream Cardigan Girl",
    nameKey: "dreamSkin.theme.campusCardiganGirl.name",
    descriptionKey: "dreamSkin.theme.campusCardiganGirl.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-campus-cardigan-girl/background.jpg", import.meta.url).href,
    tone: "modern-female",
    appearance: "light",
  },
  {
    id: "preset-bookstore-spring-girl",
    englishName: "Bookstore Spring",
    nameKey: "dreamSkin.theme.bookstoreSpringGirl.name",
    descriptionKey: "dreamSkin.theme.bookstoreSpringGirl.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-bookstore-spring-girl/background.jpg", import.meta.url).href,
    tone: "modern-female",
    appearance: "light",
  },
  {
    id: "preset-cafe-strawberry-girl",
    englishName: "Strawberry Café Girl",
    nameKey: "dreamSkin.theme.cafeStrawberryGirl.name",
    descriptionKey: "dreamSkin.theme.cafeStrawberryGirl.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-cafe-strawberry-girl/background.jpg", import.meta.url).href,
    tone: "modern-female",
    appearance: "light",
  },
  {
    id: "preset-film-camera-girl",
    englishName: "Film Camera Girl",
    nameKey: "dreamSkin.theme.filmCameraGirl.name",
    descriptionKey: "dreamSkin.theme.filmCameraGirl.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-film-camera-girl/background.jpg", import.meta.url).href,
    tone: "modern-female",
    appearance: "light",
  },
  {
    id: "preset-west-lake-morning",
    englishName: "West Lake Morning",
    nameKey: "dreamSkin.theme.westLakeMorning.name",
    descriptionKey: "dreamSkin.theme.westLakeMorning.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-west-lake-morning/background.jpg", import.meta.url).href,
    tone: "china-landscape",
    appearance: "light",
  },
  {
    id: "preset-guilin-cloud-sea",
    englishName: "Guilin Cloud Sea",
    nameKey: "dreamSkin.theme.guilinCloudSea.name",
    descriptionKey: "dreamSkin.theme.guilinCloudSea.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-guilin-cloud-sea/background.jpg", import.meta.url).href,
    tone: "china-landscape",
    appearance: "light",
  },
  {
    id: "preset-huangshan-sunrise",
    englishName: "Huangshan Sunrise",
    nameKey: "dreamSkin.theme.huangshanSunrise.name",
    descriptionKey: "dreamSkin.theme.huangshanSunrise.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-huangshan-sunrise/background.jpg", import.meta.url).href,
    tone: "china-landscape",
    appearance: "light",
  },
  {
    id: "preset-jiangnan-rain-town",
    englishName: "Jiangnan Rain Town",
    nameKey: "dreamSkin.theme.jiangnanRainTown.name",
    descriptionKey: "dreamSkin.theme.jiangnanRainTown.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-jiangnan-rain-town/background.jpg", import.meta.url).href,
    tone: "china-landscape",
    appearance: "light",
  },
  {
    id: "preset-ultraman-tiga-sky",
    englishName: "Ultraman Tiga Sky",
    nameKey: "dreamSkin.theme.ultramanTigaSky.name",
    descriptionKey: "dreamSkin.theme.ultramanTigaSky.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-ultraman-tiga-sky/background.jpg", import.meta.url).href,
    tone: "ultraman",
    appearance: "light",
  },
  {
    id: "preset-ultraman-zero-cosmos",
    englishName: "Ultraman Zero Cosmos",
    nameKey: "dreamSkin.theme.ultramanZeroCosmos.name",
    descriptionKey: "dreamSkin.theme.ultramanZeroCosmos.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-ultraman-zero-cosmos/background.jpg", import.meta.url).href,
    tone: "ultraman",
    appearance: "dark",
  },
  {
    id: "preset-ultraman-mebius-dawn",
    englishName: "Ultraman Mebius Dawn",
    nameKey: "dreamSkin.theme.ultramanMebiusDawn.name",
    descriptionKey: "dreamSkin.theme.ultramanMebiusDawn.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-ultraman-mebius-dawn/background.jpg", import.meta.url).href,
    tone: "ultraman",
    appearance: "light",
  },
  {
    id: "preset-ultraman-z-starlight",
    englishName: "Ultraman Z Starlight",
    nameKey: "dreamSkin.theme.ultramanZStarlight.name",
    descriptionKey: "dreamSkin.theme.ultramanZStarlight.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-ultraman-z-starlight/background.jpg", import.meta.url).href,
    tone: "ultraman",
    appearance: "dark",
  },
  {
    id: "preset-doraemon-anywhere-door",
    englishName: "Anywhere Door Day",
    nameKey: "dreamSkin.theme.doraemonAnywhereDoor.name",
    descriptionKey: "dreamSkin.theme.doraemonAnywhereDoor.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-doraemon-anywhere-door/background.jpg", import.meta.url).href,
    tone: "doraemon",
    appearance: "light",
  },
  {
    id: "preset-doraemon-bamboo-copter",
    englishName: "Bamboo-Copter Flight",
    nameKey: "dreamSkin.theme.doraemonBambooCopter.name",
    descriptionKey: "dreamSkin.theme.doraemonBambooCopter.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-doraemon-bamboo-copter/background.jpg", import.meta.url).href,
    tone: "doraemon",
    appearance: "light",
  },
  {
    id: "preset-doraemon-time-machine",
    englishName: "Time Machine Voyage",
    nameKey: "dreamSkin.theme.doraemonTimeMachine.name",
    descriptionKey: "dreamSkin.theme.doraemonTimeMachine.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-doraemon-time-machine/background.jpg", import.meta.url).href,
    tone: "doraemon",
    appearance: "dark",
  },
  {
    id: "preset-doraemon-nobita-night",
    englishName: "Doraemon Summer Night",
    nameKey: "dreamSkin.theme.doraemonNobitaNight.name",
    descriptionKey: "dreamSkin.theme.doraemonNobitaNight.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-doraemon-nobita-night/background.jpg", import.meta.url).href,
    tone: "doraemon",
    appearance: "dark",
  },
  {
    id: "preset-tom-jerry-kitchen-chase",
    englishName: "Kitchen Chase",
    nameKey: "dreamSkin.theme.tomJerryKitchenChase.name",
    descriptionKey: "dreamSkin.theme.tomJerryKitchenChase.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-tom-jerry-kitchen-chase/background.jpg", import.meta.url).href,
    tone: "tom-jerry",
    appearance: "light",
  },
  {
    id: "preset-tom-jerry-piano-duet",
    englishName: "Piano Mischief",
    nameKey: "dreamSkin.theme.tomJerryPianoDuet.name",
    descriptionKey: "dreamSkin.theme.tomJerryPianoDuet.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-tom-jerry-piano-duet/background.jpg", import.meta.url).href,
    tone: "tom-jerry",
    appearance: "light",
  },
  {
    id: "preset-tom-jerry-garden-picnic",
    englishName: "Garden Picnic",
    nameKey: "dreamSkin.theme.tomJerryGardenPicnic.name",
    descriptionKey: "dreamSkin.theme.tomJerryGardenPicnic.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-tom-jerry-garden-picnic/background.jpg", import.meta.url).href,
    tone: "tom-jerry",
    appearance: "light",
  },
  {
    id: "preset-tom-jerry-starry-night",
    englishName: "Rooftop Stars",
    nameKey: "dreamSkin.theme.tomJerryStarryNight.name",
    descriptionKey: "dreamSkin.theme.tomJerryStarryNight.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-tom-jerry-starry-night/background.jpg", import.meta.url).href,
    tone: "tom-jerry",
    appearance: "dark",
  },
  {
    id: "preset-spongebob-patrick-jellyfish",
    englishName: "Jellyfish Fields",
    nameKey: "dreamSkin.theme.spongebobPatrickJellyfish.name",
    descriptionKey: "dreamSkin.theme.spongebobPatrickJellyfish.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-spongebob-patrick-jellyfish/background.jpg", import.meta.url).href,
    tone: "spongebob",
    appearance: "light",
  },
  {
    id: "preset-spongebob-patrick-pineapple",
    englishName: "Pineapple House Friends",
    nameKey: "dreamSkin.theme.spongebobPatrickPineapple.name",
    descriptionKey: "dreamSkin.theme.spongebobPatrickPineapple.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-spongebob-patrick-pineapple/background.jpg", import.meta.url).href,
    tone: "spongebob",
    appearance: "light",
  },
  {
    id: "preset-spongebob-patrick-krusty-krab",
    englishName: "Krusty Krab Fun",
    nameKey: "dreamSkin.theme.spongebobPatrickKrustyKrab.name",
    descriptionKey: "dreamSkin.theme.spongebobPatrickKrustyKrab.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-spongebob-patrick-krusty-krab/background.jpg", import.meta.url).href,
    tone: "spongebob",
    appearance: "light",
  },
  {
    id: "preset-spongebob-patrick-starry-sea",
    englishName: "Bikini Bottom Stars",
    nameKey: "dreamSkin.theme.spongebobPatrickStarrySea.name",
    descriptionKey: "dreamSkin.theme.spongebobPatrickStarrySea.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-spongebob-patrick-starry-sea/background.jpg", import.meta.url).href,
    tone: "spongebob",
    appearance: "dark",
  },
  {
    id: "preset-boonie-bears-forest-day",
    englishName: "Forest Friends Day",
    nameKey: "dreamSkin.theme.boonieBearsForestDay.name",
    descriptionKey: "dreamSkin.theme.boonieBearsForestDay.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-boonie-bears-forest-day/background.jpg", import.meta.url).href,
    tone: "boonie-bears",
    appearance: "light",
  },
  {
    id: "preset-boonie-bears-snow-adventure",
    englishName: "Snow Adventure",
    nameKey: "dreamSkin.theme.boonieBearsSnowAdventure.name",
    descriptionKey: "dreamSkin.theme.boonieBearsSnowAdventure.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-boonie-bears-snow-adventure/background.jpg", import.meta.url).href,
    tone: "boonie-bears",
    appearance: "light",
  },
  {
    id: "preset-boonie-bears-treehouse",
    englishName: "Woodland Cabin",
    nameKey: "dreamSkin.theme.boonieBearsTreehouse.name",
    descriptionKey: "dreamSkin.theme.boonieBearsTreehouse.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-boonie-bears-treehouse/background.jpg", import.meta.url).href,
    tone: "boonie-bears",
    appearance: "light",
  },
  {
    id: "preset-boonie-bears-spring-picnic",
    englishName: "Spring Picnic",
    nameKey: "dreamSkin.theme.boonieBearsSpringPicnic.name",
    descriptionKey: "dreamSkin.theme.boonieBearsSpringPicnic.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-boonie-bears-spring-picnic/background.jpg", import.meta.url).href,
    tone: "boonie-bears",
    appearance: "light",
  },
  {
    id: "preset-pleasant-goat-grassland",
    englishName: "Green Grassland Day",
    nameKey: "dreamSkin.theme.pleasantGoatGrassland.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatGrassland.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-pleasant-goat-grassland/background.jpg", import.meta.url).href,
    tone: "pleasant-goat",
    appearance: "light",
  },
  {
    id: "preset-pleasant-goat-wolffy-chase",
    englishName: "Grassland Chase",
    nameKey: "dreamSkin.theme.pleasantGoatWolffyChase.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatWolffyChase.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-pleasant-goat-wolffy-chase/background.jpg", import.meta.url).href,
    tone: "pleasant-goat",
    appearance: "light",
  },
  {
    id: "preset-pleasant-goat-lantern-night",
    englishName: "Grassland Lantern Night",
    nameKey: "dreamSkin.theme.pleasantGoatLanternNight.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatLanternNight.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-pleasant-goat-lantern-night/background.jpg", import.meta.url).href,
    tone: "pleasant-goat",
    appearance: "dark",
  },
  {
    id: "preset-pleasant-goat-friends-picnic",
    englishName: "Sheep Village Picnic",
    nameKey: "dreamSkin.theme.pleasantGoatFriendsPicnic.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatFriendsPicnic.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-pleasant-goat-friends-picnic/background.jpg", import.meta.url).href,
    tone: "pleasant-goat",
    appearance: "light",
  },
  {
    id: "preset-qin-moon-tianming-shaoyu",
    englishName: "Tianming & Shaoyu",
    nameKey: "dreamSkin.theme.qinMoonTianmingShaoyu.name",
    descriptionKey: "dreamSkin.theme.qinMoonTianmingShaoyu.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-qin-moon-tianming-shaoyu/background.jpg", import.meta.url).href,
    tone: "qin-moon",
    appearance: "light",
  },
  {
    id: "preset-qin-moon-gai-nie",
    englishName: "Gai Nie Sword Intent",
    nameKey: "dreamSkin.theme.qinMoonGaiNie.name",
    descriptionKey: "dreamSkin.theme.qinMoonGaiNie.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-qin-moon-gai-nie/background.jpg", import.meta.url).href,
    tone: "qin-moon",
    appearance: "dark",
  },
  {
    id: "preset-qin-moon-wei-zhuang",
    englishName: "Wei Zhuang Cold Edge",
    nameKey: "dreamSkin.theme.qinMoonWeiZhuang.name",
    descriptionKey: "dreamSkin.theme.qinMoonWeiZhuang.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-qin-moon-wei-zhuang/background.jpg", import.meta.url).href,
    tone: "qin-moon",
    appearance: "dark",
  },
  {
    id: "preset-qin-moon-shaosiming",
    englishName: "Shao Siming Leaves",
    nameKey: "dreamSkin.theme.qinMoonShaosiming.name",
    descriptionKey: "dreamSkin.theme.qinMoonShaosiming.description",
    preview: new URL("../src-tauri/resources/dream-skin/presets/preset-qin-moon-shaosiming/background.jpg", import.meta.url).href,
    tone: "qin-moon",
    appearance: "light",
  },
] as const satisfies readonly BuiltInDreamSkinTheme[];

export const BUILT_IN_DREAM_SKIN_IDS: ReadonlySet<string> = new Set(
  BUILT_IN_DREAM_SKIN_THEMES.map((theme) => theme.id),
);
