import type { BuiltInDreamSkinTheme } from "./dreamSkinBuiltIns";

export const GENERATED_DREAM_SKIN_THEMES = [
  {
    id: "preset-tom-jerry-attic-treasure",
    englishName: "Attic Treasure Hunt",
    nameKey: "dreamSkin.theme.tomJerryAtticTreasure.name",
    descriptionKey: "dreamSkin.theme.tomJerryAtticTreasure.description",
    tone: "tom-jerry",
    appearance: "light",
  },
  {
    id: "preset-tom-jerry-beach-sandcastle",
    englishName: "Beach Sandcastle",
    nameKey: "dreamSkin.theme.tomJerryBeachSandcastle.name",
    descriptionKey: "dreamSkin.theme.tomJerryBeachSandcastle.description",
    tone: "tom-jerry",
    appearance: "light",
  },
  {
    id: "preset-tom-jerry-magic-theater",
    englishName: "Magic Theater",
    nameKey: "dreamSkin.theme.tomJerryMagicTheater.name",
    descriptionKey: "dreamSkin.theme.tomJerryMagicTheater.description",
    tone: "tom-jerry",
    appearance: "light",
  },
  {
    id: "preset-tom-jerry-rainy-window-truce",
    englishName: "Rainy Window Truce",
    nameKey: "dreamSkin.theme.tomJerryRainyWindowTruce.name",
    descriptionKey: "dreamSkin.theme.tomJerryRainyWindowTruce.description",
    tone: "tom-jerry",
    appearance: "light",
  },
  {
    id: "preset-tom-jerry-winter-ice-skating",
    englishName: "Winter Ice Skating",
    nameKey: "dreamSkin.theme.tomJerryWinterIceSkating.name",
    descriptionKey: "dreamSkin.theme.tomJerryWinterIceSkating.description",
    tone: "tom-jerry",
    appearance: "light",
  },
  {
    id: "preset-tom-jerry-train-compartment",
    englishName: "Express Train Chase",
    nameKey: "dreamSkin.theme.tomJerryTrainCompartment.name",
    descriptionKey: "dreamSkin.theme.tomJerryTrainCompartment.description",
    tone: "tom-jerry",
    appearance: "light",
  },
  {
    id: "preset-tom-jerry-candy-workshop",
    englishName: "Candy Workshop",
    nameKey: "dreamSkin.theme.tomJerryCandyWorkshop.name",
    descriptionKey: "dreamSkin.theme.tomJerryCandyWorkshop.description",
    tone: "tom-jerry",
    appearance: "light",
  },
  {
    id: "preset-tom-jerry-museum-midnight",
    englishName: "Museum at Midnight",
    nameKey: "dreamSkin.theme.tomJerryMuseumMidnight.name",
    descriptionKey: "dreamSkin.theme.tomJerryMuseumMidnight.description",
    tone: "tom-jerry",
    appearance: "dark",
  },
  {
    id: "preset-tom-jerry-moonlit-carnival",
    englishName: "Moonlit Carnival",
    nameKey: "dreamSkin.theme.tomJerryMoonlitCarnival.name",
    descriptionKey: "dreamSkin.theme.tomJerryMoonlitCarnival.description",
    tone: "tom-jerry",
    appearance: "dark",
  },
  {
    id: "preset-tom-jerry-autumn-leaf-race",
    englishName: "Autumn Leaf Race",
    nameKey: "dreamSkin.theme.tomJerryAutumnLeafRace.name",
    descriptionKey: "dreamSkin.theme.tomJerryAutumnLeafRace.description",
    tone: "tom-jerry",
    appearance: "light",
  },
  {
    id: "preset-doraemon-gadget-workshop",
    englishName: "Gadget Workshop",
    nameKey: "dreamSkin.theme.doraemonGadgetWorkshop.name",
    descriptionKey: "dreamSkin.theme.doraemonGadgetWorkshop.description",
    tone: "doraemon",
    appearance: "light",
  },
  {
    id: "preset-doraemon-cloud-kingdom",
    englishName: "Cloud Kingdom",
    nameKey: "dreamSkin.theme.doraemonCloudKingdom.name",
    descriptionKey: "dreamSkin.theme.doraemonCloudKingdom.description",
    tone: "doraemon",
    appearance: "light",
  },
  {
    id: "preset-doraemon-moon-rabbit-picnic",
    englishName: "Moon Rabbit Picnic",
    nameKey: "dreamSkin.theme.doraemonMoonRabbitPicnic.name",
    descriptionKey: "dreamSkin.theme.doraemonMoonRabbitPicnic.description",
    tone: "doraemon",
    appearance: "dark",
  },
  {
    id: "preset-doraemon-ocean-submarine",
    englishName: "Ocean Submarine",
    nameKey: "dreamSkin.theme.doraemonOceanSubmarine.name",
    descriptionKey: "dreamSkin.theme.doraemonOceanSubmarine.description",
    tone: "doraemon",
    appearance: "light",
  },
  {
    id: "preset-doraemon-snowman-festival",
    englishName: "Snowman Festival",
    nameKey: "dreamSkin.theme.doraemonSnowmanFestival.name",
    descriptionKey: "dreamSkin.theme.doraemonSnowmanFestival.description",
    tone: "doraemon",
    appearance: "light",
  },
  {
    id: "preset-doraemon-dinosaur-valley",
    englishName: "Dinosaur Valley",
    nameKey: "dreamSkin.theme.doraemonDinosaurValley.name",
    descriptionKey: "dreamSkin.theme.doraemonDinosaurValley.description",
    tone: "doraemon",
    appearance: "light",
  },
  {
    id: "preset-doraemon-space-train",
    englishName: "Space Train",
    nameKey: "dreamSkin.theme.doraemonSpaceTrain.name",
    descriptionKey: "dreamSkin.theme.doraemonSpaceTrain.description",
    tone: "doraemon",
    appearance: "light",
  },
  {
    id: "preset-doraemon-sakura-classroom",
    englishName: "Sakura Classroom",
    nameKey: "dreamSkin.theme.doraemonSakuraClassroom.name",
    descriptionKey: "dreamSkin.theme.doraemonSakuraClassroom.description",
    tone: "doraemon",
    appearance: "light",
  },
  {
    id: "preset-doraemon-desert-time-portal",
    englishName: "Desert Time Portal",
    nameKey: "dreamSkin.theme.doraemonDesertTimePortal.name",
    descriptionKey: "dreamSkin.theme.doraemonDesertTimePortal.description",
    tone: "doraemon",
    appearance: "light",
  },
  {
    id: "preset-doraemon-miniature-city",
    englishName: "Miniature City",
    nameKey: "dreamSkin.theme.doraemonMiniatureCity.name",
    descriptionKey: "dreamSkin.theme.doraemonMiniatureCity.description",
    tone: "doraemon",
    appearance: "light",
  },
  {
    id: "preset-spongebob-seashell-carousel",
    englishName: "Seashell Carousel",
    nameKey: "dreamSkin.theme.spongebobSeashellCarousel.name",
    descriptionKey: "dreamSkin.theme.spongebobSeashellCarousel.description",
    tone: "spongebob",
    appearance: "light",
  },
  {
    id: "preset-spongebob-coral-library",
    englishName: "Coral Library",
    nameKey: "dreamSkin.theme.spongebobCoralLibrary.name",
    descriptionKey: "dreamSkin.theme.spongebobCoralLibrary.description",
    tone: "spongebob",
    appearance: "light",
  },
  {
    id: "preset-spongebob-beach-band",
    englishName: "Beach Band",
    nameKey: "dreamSkin.theme.spongebobBeachBand.name",
    descriptionKey: "dreamSkin.theme.spongebobBeachBand.description",
    tone: "spongebob",
    appearance: "light",
  },
  {
    id: "preset-spongebob-snail-birthday",
    englishName: "Gary's Birthday",
    nameKey: "dreamSkin.theme.spongebobSnailBirthday.name",
    descriptionKey: "dreamSkin.theme.spongebobSnailBirthday.description",
    tone: "spongebob",
    appearance: "light",
  },
  {
    id: "preset-spongebob-kelp-garden",
    englishName: "Glowing Kelp Garden",
    nameKey: "dreamSkin.theme.spongebobKelpGarden.name",
    descriptionKey: "dreamSkin.theme.spongebobKelpGarden.description",
    tone: "spongebob",
    appearance: "light",
  },
  {
    id: "preset-spongebob-moon-jelly-cafe",
    englishName: "Moon Jelly Cafe",
    nameKey: "dreamSkin.theme.spongebobMoonJellyCafe.name",
    descriptionKey: "dreamSkin.theme.spongebobMoonJellyCafe.description",
    tone: "spongebob",
    appearance: "dark",
  },
  {
    id: "preset-spongebob-coral-art-studio",
    englishName: "Coral Art Studio",
    nameKey: "dreamSkin.theme.spongebobCoralArtStudio.name",
    descriptionKey: "dreamSkin.theme.spongebobCoralArtStudio.description",
    tone: "spongebob",
    appearance: "light",
  },
  {
    id: "preset-spongebob-rainbow-reef",
    englishName: "Rainbow Reef",
    nameKey: "dreamSkin.theme.spongebobRainbowReef.name",
    descriptionKey: "dreamSkin.theme.spongebobRainbowReef.description",
    tone: "spongebob",
    appearance: "light",
  },
  {
    id: "preset-spongebob-pearl-observatory",
    englishName: "Pearl Observatory",
    nameKey: "dreamSkin.theme.spongebobPearlObservatory.name",
    descriptionKey: "dreamSkin.theme.spongebobPearlObservatory.description",
    tone: "spongebob",
    appearance: "light",
  },
  {
    id: "preset-spongebob-pirate-parade",
    englishName: "Pirate Parade",
    nameKey: "dreamSkin.theme.spongebobPirateParade.name",
    descriptionKey: "dreamSkin.theme.spongebobPirateParade.description",
    tone: "spongebob",
    appearance: "light",
  },
  {
    id: "preset-ultraman-dyna-nebula",
    englishName: "Ultraman Dyna Nebula",
    nameKey: "dreamSkin.theme.ultramanDynaNebula.name",
    descriptionKey: "dreamSkin.theme.ultramanDynaNebula.description",
    tone: "ultraman",
    appearance: "dark",
  },
  {
    id: "preset-ultraman-gaia-earth",
    englishName: "Ultraman Gaia Earth",
    nameKey: "dreamSkin.theme.ultramanGaiaEarth.name",
    descriptionKey: "dreamSkin.theme.ultramanGaiaEarth.description",
    tone: "ultraman",
    appearance: "light",
  },
  {
    id: "preset-ultraman-nexus-crimson",
    englishName: "Ultraman Nexus Crimson",
    nameKey: "dreamSkin.theme.ultramanNexusCrimson.name",
    descriptionKey: "dreamSkin.theme.ultramanNexusCrimson.description",
    tone: "ultraman",
    appearance: "dark",
  },
  {
    id: "preset-ultraman-orb-galaxy",
    englishName: "Ultraman Orb Galaxy",
    nameKey: "dreamSkin.theme.ultramanOrbGalaxy.name",
    descriptionKey: "dreamSkin.theme.ultramanOrbGalaxy.description",
    tone: "ultraman",
    appearance: "dark",
  },
  {
    id: "preset-ultraman-geed-city-night",
    englishName: "Ultraman Geed City Night",
    nameKey: "dreamSkin.theme.ultramanGeedCityNight.name",
    descriptionKey: "dreamSkin.theme.ultramanGeedCityNight.description",
    tone: "ultraman",
    appearance: "dark",
  },
  {
    id: "preset-ultraman-taiga-sunrise",
    englishName: "Ultraman Taiga Sunrise",
    nameKey: "dreamSkin.theme.ultramanTaigaSunrise.name",
    descriptionKey: "dreamSkin.theme.ultramanTaigaSunrise.description",
    tone: "ultraman",
    appearance: "light",
  },
  {
    id: "preset-ultraman-trigger-ruins",
    englishName: "Ultraman Trigger Ruins",
    nameKey: "dreamSkin.theme.ultramanTriggerRuins.name",
    descriptionKey: "dreamSkin.theme.ultramanTriggerRuins.description",
    tone: "ultraman",
    appearance: "light",
  },
  {
    id: "preset-ultraman-decker-ocean",
    englishName: "Ultraman Decker Ocean",
    nameKey: "dreamSkin.theme.ultramanDeckerOcean.name",
    descriptionKey: "dreamSkin.theme.ultramanDeckerOcean.description",
    tone: "ultraman",
    appearance: "light",
  },
  {
    id: "preset-ultraman-blazar-thunder",
    englishName: "Ultraman Blazar Thunder",
    nameKey: "dreamSkin.theme.ultramanBlazarThunder.name",
    descriptionKey: "dreamSkin.theme.ultramanBlazarThunder.description",
    tone: "ultraman",
    appearance: "light",
  },
  {
    id: "preset-ultraman-ace-meteor",
    englishName: "Ultraman Ace Meteor",
    nameKey: "dreamSkin.theme.ultramanAceMeteor.name",
    descriptionKey: "dreamSkin.theme.ultramanAceMeteor.description",
    tone: "ultraman",
    appearance: "light",
  },
  {
    id: "preset-lotso-strawberry-bedroom",
    englishName: "Strawberry Milk Bedroom",
    nameKey: "dreamSkin.theme.lotsoStrawberryBedroom.name",
    descriptionKey: "dreamSkin.theme.lotsoStrawberryBedroom.description",
    tone: "lotso",
    appearance: "light",
  },
  {
    id: "preset-lotso-cake-shop",
    englishName: "Strawberry Cake Shop",
    nameKey: "dreamSkin.theme.lotsoCakeShop.name",
    descriptionKey: "dreamSkin.theme.lotsoCakeShop.description",
    tone: "lotso",
    appearance: "light",
  },
  {
    id: "preset-lotso-cherry-picnic",
    englishName: "Cherry Blossom Picnic",
    nameKey: "dreamSkin.theme.lotsoCherryPicnic.name",
    descriptionKey: "dreamSkin.theme.lotsoCherryPicnic.description",
    tone: "lotso",
    appearance: "light",
  },
  {
    id: "preset-lotso-cloud-swing",
    englishName: "Cloud Swing",
    nameKey: "dreamSkin.theme.lotsoCloudSwing.name",
    descriptionKey: "dreamSkin.theme.lotsoCloudSwing.description",
    tone: "lotso",
    appearance: "light",
  },
  {
    id: "preset-lotso-seaside-sundae",
    englishName: "Seaside Sundae",
    nameKey: "dreamSkin.theme.lotsoSeasideSundae.name",
    descriptionKey: "dreamSkin.theme.lotsoSeasideSundae.description",
    tone: "lotso",
    appearance: "light",
  },
  {
    id: "preset-lotso-winter-cocoa",
    englishName: "Winter Cocoa",
    nameKey: "dreamSkin.theme.lotsoWinterCocoa.name",
    descriptionKey: "dreamSkin.theme.lotsoWinterCocoa.description",
    tone: "lotso",
    appearance: "light",
  },
  {
    id: "preset-lotso-flower-greenhouse",
    englishName: "Flower Greenhouse",
    nameKey: "dreamSkin.theme.lotsoFlowerGreenhouse.name",
    descriptionKey: "dreamSkin.theme.lotsoFlowerGreenhouse.description",
    tone: "lotso",
    appearance: "light",
  },
  {
    id: "preset-lotso-moonlit-dream",
    englishName: "Moonlit Plush Dream",
    nameKey: "dreamSkin.theme.lotsoMoonlitDream.name",
    descriptionKey: "dreamSkin.theme.lotsoMoonlitDream.description",
    tone: "lotso",
    appearance: "dark",
  },
  {
    id: "preset-lotso-rainbow-candy",
    englishName: "Rainbow Candy Day",
    nameKey: "dreamSkin.theme.lotsoRainbowCandy.name",
    descriptionKey: "dreamSkin.theme.lotsoRainbowCandy.description",
    tone: "lotso",
    appearance: "light",
  },
  {
    id: "preset-lotso-autumn-knit",
    englishName: "Autumn Knitting",
    nameKey: "dreamSkin.theme.lotsoAutumnKnit.name",
    descriptionKey: "dreamSkin.theme.lotsoAutumnKnit.description",
    tone: "lotso",
    appearance: "light",
  },
  {
    id: "preset-teletubbies-sunrise-meadow",
    englishName: "Sunrise Meadow",
    nameKey: "dreamSkin.theme.teletubbiesSunriseMeadow.name",
    descriptionKey: "dreamSkin.theme.teletubbiesSunriseMeadow.description",
    tone: "teletubbies",
    appearance: "light",
  },
  {
    id: "preset-teletubbies-rainbow-puddles",
    englishName: "Rainbow Puddles",
    nameKey: "dreamSkin.theme.teletubbiesRainbowPuddles.name",
    descriptionKey: "dreamSkin.theme.teletubbiesRainbowPuddles.description",
    tone: "teletubbies",
    appearance: "light",
  },
  {
    id: "preset-teletubbies-snowy-hill",
    englishName: "Snowy Hill",
    nameKey: "dreamSkin.theme.teletubbiesSnowyHill.name",
    descriptionKey: "dreamSkin.theme.teletubbiesSnowyHill.description",
    tone: "teletubbies",
    appearance: "light",
  },
  {
    id: "preset-teletubbies-bubble-dance",
    englishName: "Bubble Dance",
    nameKey: "dreamSkin.theme.teletubbiesBubbleDance.name",
    descriptionKey: "dreamSkin.theme.teletubbiesBubbleDance.description",
    tone: "teletubbies",
    appearance: "light",
  },
  {
    id: "preset-teletubbies-flower-train",
    englishName: "Flower Train",
    nameKey: "dreamSkin.theme.teletubbiesFlowerTrain.name",
    descriptionKey: "dreamSkin.theme.teletubbiesFlowerTrain.description",
    tone: "teletubbies",
    appearance: "light",
  },
  {
    id: "preset-teletubbies-moon-lantern",
    englishName: "Moon Lantern Night",
    nameKey: "dreamSkin.theme.teletubbiesMoonLantern.name",
    descriptionKey: "dreamSkin.theme.teletubbiesMoonLantern.description",
    tone: "teletubbies",
    appearance: "dark",
  },
  {
    id: "preset-teletubbies-kite-day",
    englishName: "Kite Day",
    nameKey: "dreamSkin.theme.teletubbiesKiteDay.name",
    descriptionKey: "dreamSkin.theme.teletubbiesKiteDay.description",
    tone: "teletubbies",
    appearance: "light",
  },
  {
    id: "preset-teletubbies-picnic-blanket",
    englishName: "Picnic Blanket",
    nameKey: "dreamSkin.theme.teletubbiesPicnicBlanket.name",
    descriptionKey: "dreamSkin.theme.teletubbiesPicnicBlanket.description",
    tone: "teletubbies",
    appearance: "light",
  },
  {
    id: "preset-teletubbies-seaside-shells",
    englishName: "Seaside Shells",
    nameKey: "dreamSkin.theme.teletubbiesSeasideShells.name",
    descriptionKey: "dreamSkin.theme.teletubbiesSeasideShells.description",
    tone: "teletubbies",
    appearance: "light",
  },
  {
    id: "preset-teletubbies-star-sleepover",
    englishName: "Star Sleepover",
    nameKey: "dreamSkin.theme.teletubbiesStarSleepover.name",
    descriptionKey: "dreamSkin.theme.teletubbiesStarSleepover.description",
    tone: "teletubbies",
    appearance: "dark",
  },
  {
    id: "preset-little-carp-dragon-gate",
    englishName: "Leap Toward Dragon Gate",
    nameKey: "dreamSkin.theme.littleCarpDragonGate.name",
    descriptionKey: "dreamSkin.theme.littleCarpDragonGate.description",
    tone: "little-carp",
    appearance: "light",
  },
  {
    id: "preset-little-carp-lotus-meimei",
    englishName: "Meimei's Lotus Pond",
    nameKey: "dreamSkin.theme.littleCarpLotusMeimei.name",
    descriptionKey: "dreamSkin.theme.littleCarpLotusMeimei.description",
    tone: "little-carp",
    appearance: "light",
  },
  {
    id: "preset-little-carp-volcano-courage",
    englishName: "Volcano Courage",
    nameKey: "dreamSkin.theme.littleCarpVolcanoCourage.name",
    descriptionKey: "dreamSkin.theme.littleCarpVolcanoCourage.description",
    tone: "little-carp",
    appearance: "light",
  },
  {
    id: "preset-little-carp-moon-river-turtle",
    englishName: "Moon River Journey",
    nameKey: "dreamSkin.theme.littleCarpMoonRiverTurtle.name",
    descriptionKey: "dreamSkin.theme.littleCarpMoonRiverTurtle.description",
    tone: "little-carp",
    appearance: "dark",
  },
  {
    id: "preset-little-carp-rainbow-waterfall",
    englishName: "Rainbow Waterfall",
    nameKey: "dreamSkin.theme.littleCarpRainbowWaterfall.name",
    descriptionKey: "dreamSkin.theme.littleCarpRainbowWaterfall.description",
    tone: "little-carp",
    appearance: "light",
  },
  {
    id: "preset-little-carp-coral-palace",
    englishName: "Coral Palace",
    nameKey: "dreamSkin.theme.littleCarpCoralPalace.name",
    descriptionKey: "dreamSkin.theme.littleCarpCoralPalace.description",
    tone: "little-carp",
    appearance: "light",
  },
  {
    id: "preset-little-carp-bamboo-stream",
    englishName: "Bamboo Stream",
    nameKey: "dreamSkin.theme.littleCarpBambooStream.name",
    descriptionKey: "dreamSkin.theme.littleCarpBambooStream.description",
    tone: "little-carp",
    appearance: "light",
  },
  {
    id: "preset-little-carp-snow-pearl",
    englishName: "Snow Mountain Pearl",
    nameKey: "dreamSkin.theme.littleCarpSnowPearl.name",
    descriptionKey: "dreamSkin.theme.littleCarpSnowPearl.description",
    tone: "little-carp",
    appearance: "light",
  },
  {
    id: "preset-little-carp-lantern-village",
    englishName: "Lantern Water Village",
    nameKey: "dreamSkin.theme.littleCarpLanternVillage.name",
    descriptionKey: "dreamSkin.theme.littleCarpLanternVillage.description",
    tone: "little-carp",
    appearance: "dark",
  },
  {
    id: "preset-little-carp-star-lake-promise",
    englishName: "Star Lake Promise",
    nameKey: "dreamSkin.theme.littleCarpStarLakePromise.name",
    descriptionKey: "dreamSkin.theme.littleCarpStarLakePromise.description",
    tone: "little-carp",
    appearance: "dark",
  },
  {
    id: "preset-cute-girl-strawberry-pajama",
    englishName: "Strawberry Pajama Morning",
    nameKey: "dreamSkin.theme.cuteGirlStrawberryPajama.name",
    descriptionKey: "dreamSkin.theme.cuteGirlStrawberryPajama.description",
    tone: "cute-girl",
    appearance: "light",
  },
  {
    id: "preset-cute-girl-lavender-cat-cafe",
    englishName: "Lavender Cat Cafe",
    nameKey: "dreamSkin.theme.cuteGirlLavenderCatCafe.name",
    descriptionKey: "dreamSkin.theme.cuteGirlLavenderCatCafe.description",
    tone: "cute-girl",
    appearance: "light",
  },
  {
    id: "preset-cute-girl-mint-seaside-bicycle",
    englishName: "Mint Seaside Bicycle",
    nameKey: "dreamSkin.theme.cuteGirlMintSeasideBicycle.name",
    descriptionKey: "dreamSkin.theme.cuteGirlMintSeasideBicycle.description",
    tone: "cute-girl",
    appearance: "light",
  },
  {
    id: "preset-cute-girl-peach-book-nook",
    englishName: "Peach Blossom Book Nook",
    nameKey: "dreamSkin.theme.cuteGirlPeachBookNook.name",
    descriptionKey: "dreamSkin.theme.cuteGirlPeachBookNook.description",
    tone: "cute-girl",
    appearance: "light",
  },
  {
    id: "preset-cute-girl-moon-rabbit-dream",
    englishName: "Moon Rabbit Dream",
    nameKey: "dreamSkin.theme.cuteGirlMoonRabbitDream.name",
    descriptionKey: "dreamSkin.theme.cuteGirlMoonRabbitDream.description",
    tone: "cute-girl",
    appearance: "dark",
  },
  {
    id: "preset-cute-girl-cherry-soda-arcade",
    englishName: "Cherry Soda Arcade",
    nameKey: "dreamSkin.theme.cuteGirlCherrySodaArcade.name",
    descriptionKey: "dreamSkin.theme.cuteGirlCherrySodaArcade.description",
    tone: "cute-girl",
    appearance: "light",
  },
  {
    id: "preset-cute-girl-cream-bakery",
    englishName: "Cream Bakery Morning",
    nameKey: "dreamSkin.theme.cuteGirlCreamBakery.name",
    descriptionKey: "dreamSkin.theme.cuteGirlCreamBakery.description",
    tone: "cute-girl",
    appearance: "light",
  },
  {
    id: "preset-cute-girl-sky-music-room",
    englishName: "Sky Blue Music Room",
    nameKey: "dreamSkin.theme.cuteGirlSkyMusicRoom.name",
    descriptionKey: "dreamSkin.theme.cuteGirlSkyMusicRoom.description",
    tone: "cute-girl",
    appearance: "light",
  },
  {
    id: "preset-cute-girl-hydrangea-rain",
    englishName: "Hydrangea Rain",
    nameKey: "dreamSkin.theme.cuteGirlHydrangeaRain.name",
    descriptionKey: "dreamSkin.theme.cuteGirlHydrangeaRain.description",
    tone: "cute-girl",
    appearance: "light",
  },
  {
    id: "preset-cute-girl-snow-fox-cocoa",
    englishName: "Snow Fox Cocoa",
    nameKey: "dreamSkin.theme.cuteGirlSnowFoxCocoa.name",
    descriptionKey: "dreamSkin.theme.cuteGirlSnowFoxCocoa.description",
    tone: "cute-girl",
    appearance: "light",
  },
  {
    id: "preset-boonie-bears-honey-workshop",
    englishName: "Honey Workshop",
    nameKey: "dreamSkin.theme.boonieBearsHoneyWorkshop.name",
    descriptionKey: "dreamSkin.theme.boonieBearsHoneyWorkshop.description",
    tone: "boonie-bears",
    appearance: "light",
  },
  {
    id: "preset-boonie-bears-river-rafting",
    englishName: "River Rafting",
    nameKey: "dreamSkin.theme.boonieBearsRiverRafting.name",
    descriptionKey: "dreamSkin.theme.boonieBearsRiverRafting.description",
    tone: "boonie-bears",
    appearance: "light",
  },
  {
    id: "preset-boonie-bears-sunflower-farm",
    englishName: "Sunflower Farm",
    nameKey: "dreamSkin.theme.boonieBearsSunflowerFarm.name",
    descriptionKey: "dreamSkin.theme.boonieBearsSunflowerFarm.description",
    tone: "boonie-bears",
    appearance: "light",
  },
  {
    id: "preset-boonie-bears-moon-campground",
    englishName: "Moon Campground",
    nameKey: "dreamSkin.theme.boonieBearsMoonCampground.name",
    descriptionKey: "dreamSkin.theme.boonieBearsMoonCampground.description",
    tone: "boonie-bears",
    appearance: "dark",
  },
  {
    id: "preset-boonie-bears-autumn-train",
    englishName: "Autumn Forest Train",
    nameKey: "dreamSkin.theme.boonieBearsAutumnTrain.name",
    descriptionKey: "dreamSkin.theme.boonieBearsAutumnTrain.description",
    tone: "boonie-bears",
    appearance: "light",
  },
  {
    id: "preset-boonie-bears-seaside-rescue",
    englishName: "Seaside Rescue",
    nameKey: "dreamSkin.theme.boonieBearsSeasideRescue.name",
    descriptionKey: "dreamSkin.theme.boonieBearsSeasideRescue.description",
    tone: "boonie-bears",
    appearance: "light",
  },
  {
    id: "preset-boonie-bears-bamboo-festival",
    englishName: "Bamboo Festival",
    nameKey: "dreamSkin.theme.boonieBearsBambooFestival.name",
    descriptionKey: "dreamSkin.theme.boonieBearsBambooFestival.description",
    tone: "boonie-bears",
    appearance: "light",
  },
  {
    id: "preset-boonie-bears-crystal-cave",
    englishName: "Crystal Cave",
    nameKey: "dreamSkin.theme.boonieBearsCrystalCave.name",
    descriptionKey: "dreamSkin.theme.boonieBearsCrystalCave.description",
    tone: "boonie-bears",
    appearance: "dark",
  },
  {
    id: "preset-boonie-bears-fruit-orchard",
    englishName: "Fruit Orchard",
    nameKey: "dreamSkin.theme.boonieBearsFruitOrchard.name",
    descriptionKey: "dreamSkin.theme.boonieBearsFruitOrchard.description",
    tone: "boonie-bears",
    appearance: "light",
  },
  {
    id: "preset-boonie-bears-rainy-cabin",
    englishName: "Rainy Cabin Games",
    nameKey: "dreamSkin.theme.boonieBearsRainyCabin.name",
    descriptionKey: "dreamSkin.theme.boonieBearsRainyCabin.description",
    tone: "boonie-bears",
    appearance: "light",
  },
  {
    id: "preset-pleasant-goat-science-fair",
    englishName: "Sheep Village Science Fair",
    nameKey: "dreamSkin.theme.pleasantGoatScienceFair.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatScienceFair.description",
    tone: "pleasant-goat",
    appearance: "light",
  },
  {
    id: "preset-pleasant-goat-candy-carnival",
    englishName: "Candy Carnival",
    nameKey: "dreamSkin.theme.pleasantGoatCandyCarnival.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatCandyCarnival.description",
    tone: "pleasant-goat",
    appearance: "light",
  },
  {
    id: "preset-pleasant-goat-seaside-volleyball",
    englishName: "Seaside Volleyball",
    nameKey: "dreamSkin.theme.pleasantGoatSeasideVolleyball.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatSeasideVolleyball.description",
    tone: "pleasant-goat",
    appearance: "light",
  },
  {
    id: "preset-pleasant-goat-moon-castle",
    englishName: "Moon Castle",
    nameKey: "dreamSkin.theme.pleasantGoatMoonCastle.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatMoonCastle.description",
    tone: "pleasant-goat",
    appearance: "dark",
  },
  {
    id: "preset-pleasant-goat-winter-hotpot",
    englishName: "Winter Hotpot",
    nameKey: "dreamSkin.theme.pleasantGoatWinterHotpot.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatWinterHotpot.description",
    tone: "pleasant-goat",
    appearance: "light",
  },
  {
    id: "preset-pleasant-goat-rainbow-sports",
    englishName: "Rainbow Sports Day",
    nameKey: "dreamSkin.theme.pleasantGoatRainbowSports.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatRainbowSports.description",
    tone: "pleasant-goat",
    appearance: "light",
  },
  {
    id: "preset-pleasant-goat-music-festival",
    englishName: "Grassland Music Festival",
    nameKey: "dreamSkin.theme.pleasantGoatMusicFestival.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatMusicFestival.description",
    tone: "pleasant-goat",
    appearance: "light",
  },
  {
    id: "preset-pleasant-goat-cloud-airplane",
    englishName: "Cloud Airplane",
    nameKey: "dreamSkin.theme.pleasantGoatCloudAirplane.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatCloudAirplane.description",
    tone: "pleasant-goat",
    appearance: "light",
  },
  {
    id: "preset-pleasant-goat-fruit-harvest",
    englishName: "Fruit Harvest",
    nameKey: "dreamSkin.theme.pleasantGoatFruitHarvest.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatFruitHarvest.description",
    tone: "pleasant-goat",
    appearance: "light",
  },
  {
    id: "preset-pleasant-goat-detective-mystery",
    englishName: "Little Detectives",
    nameKey: "dreamSkin.theme.pleasantGoatDetectiveMystery.name",
    descriptionKey: "dreamSkin.theme.pleasantGoatDetectiveMystery.description",
    tone: "pleasant-goat",
    appearance: "light",
  },
  {
    id: "preset-hongmao-lantu-rainbow-cliff",
    englishName: "Rainbow Cliff Promise",
    nameKey: "dreamSkin.theme.hongmaoLantuRainbowCliff.name",
    descriptionKey: "dreamSkin.theme.hongmaoLantuRainbowCliff.description",
    tone: "hongmao-lantu",
    appearance: "light",
  },
  {
    id: "preset-hongmao-lantu-bamboo-sword-dance",
    englishName: "Bamboo Sword Dance",
    nameKey: "dreamSkin.theme.hongmaoLantuBambooSwordDance.name",
    descriptionKey: "dreamSkin.theme.hongmaoLantuBambooSwordDance.description",
    tone: "hongmao-lantu",
    appearance: "light",
  },
  {
    id: "preset-hongmao-lantu-ice-palace-lanterns",
    englishName: "Ice Palace Lanterns",
    nameKey: "dreamSkin.theme.hongmaoLantuIcePalaceLanterns.name",
    descriptionKey: "dreamSkin.theme.hongmaoLantuIcePalaceLanterns.description",
    tone: "hongmao-lantu",
    appearance: "dark",
  },
  {
    id: "preset-hongmao-lantu-seven-heroes-sunrise",
    englishName: "Seven Heroes Sunrise",
    nameKey: "dreamSkin.theme.hongmaoLantuSevenHeroesSunrise.name",
    descriptionKey: "dreamSkin.theme.hongmaoLantuSevenHeroesSunrise.description",
    tone: "hongmao-lantu",
    appearance: "light",
  },
  {
    id: "preset-hongmao-lantu-moonlit-waterfall",
    englishName: "Moonlit Waterfall",
    nameKey: "dreamSkin.theme.hongmaoLantuMoonlitWaterfall.name",
    descriptionKey: "dreamSkin.theme.hongmaoLantuMoonlitWaterfall.description",
    tone: "hongmao-lantu",
    appearance: "dark",
  },
  {
    id: "preset-big-ear-tutu-rainbow-kindergarten",
    englishName: "Rainbow Kindergarten",
    nameKey: "dreamSkin.theme.bigEarTutuRainbowKindergarten.name",
    descriptionKey: "dreamSkin.theme.bigEarTutuRainbowKindergarten.description",
    tone: "big-ear-tutu",
    appearance: "light",
  },
  {
    id: "preset-big-ear-tutu-dumpling-night",
    englishName: "Family Dumpling Night",
    nameKey: "dreamSkin.theme.bigEarTutuDumplingNight.name",
    descriptionKey: "dreamSkin.theme.bigEarTutuDumplingNight.description",
    tone: "big-ear-tutu",
    appearance: "light",
  },
  {
    id: "preset-big-ear-tutu-seaside-bubbles",
    englishName: "Seaside Bubble Day",
    nameKey: "dreamSkin.theme.bigEarTutuSeasideBubbles.name",
    descriptionKey: "dreamSkin.theme.bigEarTutuSeasideBubbles.description",
    tone: "big-ear-tutu",
    appearance: "light",
  },
  {
    id: "preset-big-ear-tutu-snowy-neighborhood",
    englishName: "Snowy Neighborhood",
    nameKey: "dreamSkin.theme.bigEarTutuSnowyNeighborhood.name",
    descriptionKey: "dreamSkin.theme.bigEarTutuSnowyNeighborhood.description",
    tone: "big-ear-tutu",
    appearance: "dark",
  },
  {
    id: "preset-big-ear-tutu-starry-rooftop",
    englishName: "Starry Rooftop",
    nameKey: "dreamSkin.theme.bigEarTutuStarryRooftop.name",
    descriptionKey: "dreamSkin.theme.bigEarTutuStarryRooftop.description",
    tone: "big-ear-tutu",
    appearance: "dark",
  },
  {
    id: "preset-sanmao-spring-newspaper-lane",
    englishName: "Spring Newspaper Lane",
    nameKey: "dreamSkin.theme.sanmaoSpringNewspaperLane.name",
    descriptionKey: "dreamSkin.theme.sanmaoSpringNewspaperLane.description",
    tone: "sanmao",
    appearance: "light",
  },
  {
    id: "preset-sanmao-riverside-paper-boat",
    englishName: "Riverside Paper Boat",
    nameKey: "dreamSkin.theme.sanmaoRiversidePaperBoat.name",
    descriptionKey: "dreamSkin.theme.sanmaoRiversidePaperBoat.description",
    tone: "sanmao",
    appearance: "light",
  },
  {
    id: "preset-sanmao-warm-noodle-stall",
    englishName: "Warm Noodle Stall",
    nameKey: "dreamSkin.theme.sanmaoWarmNoodleStall.name",
    descriptionKey: "dreamSkin.theme.sanmaoWarmNoodleStall.description",
    tone: "sanmao",
    appearance: "dark",
  },
  {
    id: "preset-sanmao-lantern-wish",
    englishName: "Lantern Wish",
    nameKey: "dreamSkin.theme.sanmaoLanternWish.name",
    descriptionKey: "dreamSkin.theme.sanmaoLanternWish.description",
    tone: "sanmao",
    appearance: "dark",
  },
  {
    id: "preset-sanmao-seaside-kite",
    englishName: "Seaside Kite",
    nameKey: "dreamSkin.theme.sanmaoSeasideKite.name",
    descriptionKey: "dreamSkin.theme.sanmaoSeasideKite.description",
    tone: "sanmao",
    appearance: "light",
  },
  {
    id: "preset-xiaofugui-imperial-kitchen-dawn",
    englishName: "Imperial Kitchen Dawn",
    nameKey: "dreamSkin.theme.xiaofuguiImperialKitchenDawn.name",
    descriptionKey: "dreamSkin.theme.xiaofuguiImperialKitchenDawn.description",
    tone: "xiaofugui",
    appearance: "light",
  },
  {
    id: "preset-xiaofugui-lotus-feast",
    englishName: "Lotus Lake Feast",
    nameKey: "dreamSkin.theme.xiaofuguiLotusFeast.name",
    descriptionKey: "dreamSkin.theme.xiaofuguiLotusFeast.description",
    tone: "xiaofugui",
    appearance: "light",
  },
  {
    id: "preset-xiaofugui-lantern-market-snacks",
    englishName: "Lantern Market Snacks",
    nameKey: "dreamSkin.theme.xiaofuguiLanternMarketSnacks.name",
    descriptionKey: "dreamSkin.theme.xiaofuguiLanternMarketSnacks.description",
    tone: "xiaofugui",
    appearance: "dark",
  },
  {
    id: "preset-xiaofugui-snowy-hotpot",
    englishName: "Snowy Hotpot",
    nameKey: "dreamSkin.theme.xiaofuguiSnowyHotpot.name",
    descriptionKey: "dreamSkin.theme.xiaofuguiSnowyHotpot.description",
    tone: "xiaofugui",
    appearance: "dark",
  },
  {
    id: "preset-xiaofugui-peach-blossom-picnic",
    englishName: "Peach Blossom Picnic",
    nameKey: "dreamSkin.theme.xiaofuguiPeachBlossomPicnic.name",
    descriptionKey: "dreamSkin.theme.xiaofuguiPeachBlossomPicnic.description",
    tone: "xiaofugui",
    appearance: "light",
  },
] as const satisfies readonly BuiltInDreamSkinTheme[];
