import { StyleSheet } from 'react-native';

export const palette = { ink: '#13231c', muted: '#6f8177', green: '#14806f', border: '#dce8df',
  background: '#f7faf7', pale: '#e6f8f1', danger: '#c74e47' };

export const styles = StyleSheet.create({
  fill: { flex: 1 },
  hidden: { display: 'none' },
  page: { flex: 1, backgroundColor: palette.background },
  padded: { padding: 20, gap: 14 },
  heading: { color: palette.ink, fontSize: 27, lineHeight: 36, fontWeight: '800' },
  title: { color: palette.ink, fontSize: 16, lineHeight: 24, fontWeight: '700' },
  subtitle: { color: palette.muted, fontSize: 13, lineHeight: 20 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  card: { backgroundColor: '#fff', borderColor: palette.border, borderWidth: 1,
    borderRadius: 16, padding: 16, gap: 8 },
  button: { minHeight: 42, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10,
    backgroundColor: palette.pale, alignItems: 'center', justifyContent: 'center' },
  buttonText: { color: palette.green, fontSize: 13, lineHeight: 20, fontWeight: '700' },
  primary: { backgroundColor: palette.green },
  primaryText: { color: '#fff' },
  disabled: { opacity: 0.4 },
  header: { paddingHorizontal: 16, paddingVertical: 12, gap: 12, flexDirection: 'row',
    alignItems: 'center', borderBottomWidth: 1, borderBottomColor: palette.border, backgroundColor: '#fff' },
  headerTitle: { color: palette.ink, fontSize: 16, lineHeight: 24, fontWeight: '700' },
  // Explicit leading leaves room for Android's Chinese fallback font, including single-line labels.
  headerMeta: { color: palette.muted, fontSize: 11, lineHeight: 18, marginTop: 4 },
  back: { padding: 6, minWidth: 35, minHeight: 40, justifyContent: 'center' },
  backText: { color: palette.ink, fontSize: 25 },
  search: { borderRadius: 12, borderWidth: 1, borderColor: palette.border,
    backgroundColor: '#fff', padding: 12, color: palette.ink, fontSize: 14 },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 30, gap: 12 },
  emptyGlyph: { fontSize: 36, color: palette.green },
  centerText: { textAlign: 'center' },
  error: { color: palette.danger, fontSize: 12, lineHeight: 18, padding: 12, maxWidth: 400 },
  // Separators keep spacing inside FlatList's measured cells; container gaps can leave a blank render window.
  messages: { padding: 16 },
  messageSeparator: { height: 20 },
  messageHeader: { marginBottom: 20 },
  messageFooter: { paddingTop: 20, gap: 12 },
  messageListLoading: { opacity: 0 },
  messageLoadingOverlay: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', gap: 8 },
  // Leave room for Android's fallback font instead of relying on the exact measured text width.
  messageLoadingText: { width: '100%', maxWidth: 400, paddingHorizontal: 16, textAlign: 'center' },
  historyStatus: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, minHeight: 36 },
  userMessage: { alignSelf: 'flex-end', maxWidth: '92%', borderRadius: 18,
    backgroundColor: '#e6f1eb', paddingHorizontal: 15, paddingVertical: 10 },
  messageText: { color: palette.ink, fontSize: 15, lineHeight: 24 },
  assistantMessage: { gap: 8 },
  speaker: { color: palette.green, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  tool: { borderLeftWidth: 2, borderLeftColor: '#b7cbc0', paddingLeft: 12, paddingVertical: 8 },
  code: { fontFamily: 'monospace', color: palette.ink, fontSize: 12, lineHeight: 19 },
  status: { fontSize: 12, lineHeight: 18, color: palette.muted, marginVertical: 6 },
  composer: { padding: 12, gap: 10, backgroundColor: '#fff', borderTopWidth: 1, borderTopColor: palette.border },
  composerField: { padding: 8, gap: 4, borderWidth: 1, borderColor: palette.border,
    backgroundColor: palette.background, borderRadius: 22 },
  composerActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  composerTrailing: { flexDirection: 'row', gap: 8, alignItems: 'center', flexShrink: 1 },
  composerModel: { paddingHorizontal: 8, paddingVertical: 6, minHeight: 40, minWidth: 0,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, flexShrink: 1 },
  composerModelText: { fontSize: 13, lineHeight: 20, paddingVertical: 2, color: palette.ink,
    includeFontPadding: true, textAlignVertical: 'center', flexShrink: 1 },
  composerAdd: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 20 },
  composerAddText: { color: palette.ink, fontSize: 28, lineHeight: 32 },
  input: { minHeight: 40, maxHeight: 150, fontSize: 16, lineHeight: 23, color: palette.ink,
    paddingHorizontal: 8, paddingVertical: 8, textAlignVertical: 'top' },
  compactButton: { minHeight: 36, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10,
    backgroundColor: palette.pale, justifyContent: 'center' },
  settings: { gap: 12, maxWidth: 400, width: '100%', alignSelf: 'center' },
  choice: { padding: 12, borderWidth: 1, borderColor: palette.border, borderRadius: 12 },
  chosen: { borderColor: palette.green, backgroundColor: palette.pale },
  approval: { maxWidth: 400, width: '100%', alignSelf: 'center', borderWidth: 1,
    borderColor: '#e1ce9e', borderRadius: 14, backgroundColor: '#fffaf0', padding: 14, gap: 12 },
  questionInput: { borderWidth: 1, borderColor: palette.border, borderRadius: 9,
    padding: 10, color: palette.ink, backgroundColor: '#fff' },
});
