import { StyleSheet } from 'react-native';

// A consistent gray canvas keeps the white composer distinct, including above the keyboard.
export const palette = { ink: '#17211b', muted: '#718078', green: '#0b8065', border: '#dfe5df',
  background: '#f4f4f4', pale: '#e7f5f4', danger: '#c74e47' };

export const styles = StyleSheet.create({
  fill: { flex: 1 },
  hidden: { display: 'none' },
  page: { flex: 1, backgroundColor: palette.background },
  padded: { padding: 20, gap: 14 },
  heading: { color: palette.ink, fontSize: 27, lineHeight: 36, fontWeight: '800' },
  title: { color: palette.ink, fontSize: 16, lineHeight: 24, fontWeight: '700' },
  subtitle: { color: palette.muted, fontSize: 13, lineHeight: 20 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  card: { backgroundColor: '#fff', borderColor: palette.border, borderWidth: 1,
    borderRadius: 16, padding: 16, gap: 8 },
  button: { minHeight: 42, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10,
    backgroundColor: palette.pale, alignItems: 'center', justifyContent: 'center' },
  buttonText: { color: palette.green, fontSize: 13, lineHeight: 20, fontWeight: '700' },
  primary: { backgroundColor: palette.green },
  primaryText: { color: '#fff' },
  disabled: { opacity: 0.4 },
  header: { paddingHorizontal: 16, paddingVertical: 12, gap: 12, flexDirection: 'row',
    alignItems: 'center' },
  headerContent: { flex: 1, minWidth: 0 },
  headerTools: { flexShrink: 0, marginLeft: 'auto' },
  headerTitle: { color: palette.ink, fontSize: 16, lineHeight: 24, fontWeight: '700' },
  // Explicit leading leaves room for Android's Chinese fallback font, including single-line labels.
  headerMeta: { color: palette.muted, fontSize: 11, lineHeight: 18, marginTop: 4 },
  back: { padding: 6, minWidth: 35, minHeight: 40, justifyContent: 'center' },
  backText: { color: palette.ink, fontSize: 25 },
  search: { borderRadius: 12, borderWidth: 1, borderColor: palette.border,
    backgroundColor: '#fff', padding: 12, color: palette.ink, fontSize: 14 },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 30, gap: 12 },
  emptyGlyph: { fontSize: 36, color: palette.green },
  centerText: { textAlign: 'center' },
  error: { color: palette.danger, fontSize: 12, lineHeight: 18, padding: 12, maxWidth: 400 },
  // Separators keep spacing inside FlatList's measured cells; container gaps can leave a blank render window.
  messages: { padding: 16 },
  messageSeparator: { height: 20 },
  messageHeader: { marginBottom: 20 },
  messageFooter: { paddingTop: 20, gap: 12 },
  messageListLoading: { opacity: 0 },
  scrollToBottom: { position: 'absolute', bottom: 12, alignSelf: 'center', maxWidth: 400,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6,
    minHeight: 44, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 22,
    backgroundColor: '#fff', borderWidth: 1, borderColor: palette.border,
    elevation: 3, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  scrollToBottomPressed: { backgroundColor: palette.pale },
  scrollToBottomText: { color: palette.ink, fontSize: 13, lineHeight: 20, flexShrink: 1 },
  messageLoadingOverlay: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', gap: 8 },
  // Leave room for Android's fallback font instead of relying on the exact measured text width.
  messageLoadingText: { width: '100%', maxWidth: 400, paddingHorizontal: 16, textAlign: 'center' },
  historyStatus: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, minHeight: 36 },
  userMessage: { alignSelf: 'flex-end', maxWidth: '90%', borderRadius: 16, borderBottomRightRadius: 4,
    backgroundColor: palette.pale, paddingHorizontal: 19, paddingVertical: 15 },
  messageText: { color: palette.ink, fontSize: 14, lineHeight: 25 },
  assistantMessage: { gap: 8 },
  speaker: { color: palette.green, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  tool: { borderLeftWidth: 2, borderLeftColor: '#b7cbc0', paddingLeft: 12, paddingVertical: 8 },
  code: { fontFamily: 'monospace', color: palette.ink, fontSize: 12, lineHeight: 19 },
  status: { fontSize: 12, lineHeight: 18, color: palette.muted, marginVertical: 6 },
  // Bound the whole dock after keyboard resizing; draft content scrolls while actions stay visible.
  composerDock: { maxHeight: '75%', flexShrink: 1 },
  composer: { padding: 12, gap: 10, flexShrink: 1, minHeight: 96 },
  composerCompact: { minHeight: 80 },
  composerField: { padding: 8, gap: 4, backgroundColor: '#fff', borderRadius: 26, flexShrink: 1 },
  composerContent: { flexGrow: 0, flexShrink: 1 },
  composerContentInner: { gap: 4 },
  composerFieldCompact: { padding: 6, borderRadius: 28 },
  composerActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  composerActionsCompact: { position: 'absolute', left: 6, right: 6, top: 8 },
  composerTrailing: { flexDirection: 'row', gap: 8, alignItems: 'center', flexShrink: 1 },
  composerModel: { paddingHorizontal: 8, paddingVertical: 6, minHeight: 40, minWidth: 0,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, flexShrink: 1 },
  composerModelCompact: { width: 40, paddingHorizontal: 0 },
  composerModelText: { fontSize: 13, lineHeight: 20, paddingVertical: 2, color: palette.ink,
    includeFontPadding: true, textAlignVertical: 'center', flexShrink: 1 },
  composerAdd: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 20 },
  composerAddText: { color: palette.ink, fontSize: 28, lineHeight: 32 },
  input: { minHeight: 40, maxHeight: 150, fontSize: 16, lineHeight: 23, color: palette.ink,
    paddingHorizontal: 8, paddingVertical: 8, textAlignVertical: 'top' },
  inputCompact: { height: 44, minHeight: 44, maxHeight: 44, marginLeft: 40, marginRight: 88,
    textAlignVertical: 'center' },
  compactButton: { minHeight: 36, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10,
    backgroundColor: palette.pale, justifyContent: 'center' },
  settings: { gap: 12, maxWidth: 400, width: '100%', alignSelf: 'center' },
  choice: { padding: 12, borderWidth: 1, borderColor: palette.border, borderRadius: 12 },
  chosen: { borderColor: palette.green, backgroundColor: palette.pale },
  approval: { maxWidth: 400, width: '100%', alignSelf: 'center', borderWidth: 1,
    borderColor: '#e1ce9e', borderRadius: 14, backgroundColor: '#fffaf0', padding: 14, gap: 12 },
  questionInput: { borderWidth: 1, borderColor: palette.border, borderRadius: 9,
    padding: 10, color: palette.ink, backgroundColor: '#fff' },
});
